### ISSUE TITLE
Decimal shop economy

### ISSUE THREAD

**Issue by Yukyxy** [snowgears/shopbugs#1]
Hello, Impossible to make a shop with a decimal price...
"SnowGears said: ↑
What is your error exactly? Did you make sure your config is set to use vault as the currency rather than emeralds?"

yes : "useVault: true" no error in the console

screen: https://proxy.spigotmc.org/b1da67ca7d230ff4522f7b01ee18a4a77dbd081b?url=https%3A%2F%2Fzupimages.net%2Fup%2F18%2F49%2F2gs2.png

i use CMI and vault of cmi, in 1.12.2 it's ok but not 1.13.2 :(

**Comment by Yukyxy** [comment]
Hello, Is this going to be fixed?

**Comment by Yukyxy** [comment]
Hello, I tested by editing manually, it works. But not with the sign.

https://zupimages.net/up/19/01/cm7c.png

**Comment by gerardvanschip** [comment]
I know this is an old issue but its not clear to me if I can change it. Is it or is it not possible to create a price like 0.16?

**Comment by snowgears** [comment]
Fixed in Shop 1.8.2
