### ISSUE TITLE
Buying/ selling history

### ISSUE THREAD

**Issue by zicy** [snowgears/shopbugs#100]
**Is your feature request related to a problem? Please describe.**
No really a problem, but a lot of our players are asking if they can see who is buying their stuff when they are not online.

**Describe the solution you'd like**
When people are buying/ selling save it to a 'transaction' file/database.

Then adding a new command which could be '/shop history' where the player can see the transactions made at their shops.

I would personally like to be able to see both what other people have bought/ sold at my shops but also what I have bought/ sold to other players.

**Describe alternatives you've considered**
As far as i can see it's not currently logged, so i can't see a way to get this information.

**Comment by snowgears** [comment]
Very similar to #30 so I am calling it a duplicate.
