### ISSUE TITLE
Shop GUI glitched player heads

### ISSUE THREAD

**Issue by ItsMCB** [snowgears/shopbugs#103]
When a player makes a shop, it can sometimes bug out and produce this error. The player head does not show the correct head and when you click on it nothing happens. Reloading the plugin does not fix the issue.

In this state, some of the heads work just fine while the newer ones don't.

Broken Head:
![image](https://user-images.githubusercontent.com/33915290/89332919-ce4fef80-d659-11ea-80ef-ca5a6cfc0bb4.png)

Another head that is working:![image](https://user-images.githubusercontent.com/33915290/89334036-88942680-d65b-11ea-9af4-cae7f5cf0fcd.png)

Versions:
This server is running CraftBukkit version git-Spigot-05da6fa-b0c6dfe (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
 
The latest shop version from [Aug 13, 2019](https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/update?update=292999).

A full server restart fixes the issue. However, I shouldn't have to restart just so it can work correctly.

**Comment by snowgears** [comment]
I have still not been able to reproduce this but working on it!

**Comment by snowgears** [comment]
Should be fixed in 1.8.2.8 (in progress)
