### ISSUE TITLE
server-name parameter doesn't work in Spigot servers

### ISSUE THREAD

**Issue by syntonex** [snowgears/shopbugs#104]
**Describe the bug**

The server-name parameter doesn't work in Spigot servers. The sign displays Unknown Server.

https://www.spigotmc.org/wiki/spigot-configuration-server-properties/

**To Reproduce**

Install a Spigot server with the plugin.

**Expected behavior**

If there isn't a server-name parameter set, I good option is to use "Server" string as alternative

**Screenshots**

**Version:**

 - Spigot version: Spigot 1.16.1
 - Shop version: 1.8.1

**Additional context**
I was reading the FAQ and the GitHub bugs list but I didn't find any information to solve this problem.

**Comment by BillyGalbreath** [comment]
Spigot removed server-name from server.properties awhile back. Take it up with Spigot, or use a fork that adds it back (like [Purpur](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0010-Bring-back-server-name.patch))

**Comment by syntonex** [comment]
Thank you for your reply.

I cannot change the Spigot servers to use a different one now, that why I wrote that maybe is a good option to Spigot servers > X version with the server-name tag removed to put the string "Server" and not "Unknow Server".

Is this possible? or to define it in the config.yml?

**Comment by syntonex** [comment]
Closes, I found a method changing the signConfig.yml
