### ISSUE TITLE
Can take things from the displayed items

### ISSUE THREAD

**Issue by smallcanner** [snowgears/shopbugs#105]
I have a 1.12.2 server
Players can put items into shulker_box and remove them from above the display
That shulker_box performs item copy

**Comment by snowgears** [comment]
Can you please describe in more detail how this is done? I am having trouble reproducing this.

**Comment by snowgears** [comment]
Can you please try this in shop 1.8.2 and a supported version of Spigot (1.16+) and reopen the ticket if the issue persists.
