### ISSUE TITLE
Statistics for players

### ISSUE THREAD

**Issue by MsKnockleby** [snowgears/shopbugs#106]
I would utterly love it if players could type a command like /shop price oak_planks and see what price the item is being sold for at which locations. 

Or be able to use /shop popular
and see what the last 10 purchases (at anyone's shops) were.

Basically, my players would love to have more information about our economy.

**Comment by snowgears** [comment]
I really like this idea and have built upon it a bit with another feature request. Check out #112 and feel free to post any other suggestions in that thread! It would accomplish what you are talking about for the most part.
