### ISSUE TITLE
Multiple shops can be created on a single chest (using different sides)

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#109]
**Describe the bug**
Multiple shops can be created on a single chest (using different sides)

**To Reproduce**
1. Make a shop using one side of a chest
2. Put another shop sign on the same chest shop on a different side. This should be blocked.

**Version:**
 - Spigot version: Spigot 1.16.1
 - Shop version: 1.8.2

**Comment by tWizT3ddreaMr** [comment]
Sounds like the issue i saw with a check if there is a shop that doesn't always show if there is a shop
Will be fixed when #110 but a new check will need done for #115 to be viable with this.
I can make multiple branches to do each one, as suggest by pepper.
And hopefully my work can easily be changed to reflect whatever conventions you have. Unless these are for you

**Comment by snowgears** [comment]
Fixed in 1.8.2.1

**Comment by snowgears** [comment]
@tWizT3ddreaMr I may actually leave #110 as is and incorporate this as a feature but I am still undecided on this. My thinking is that since shulker boxes and barrels can be used in any direction for shops, why shouldn't chests? I would appreciate any other input on this though.

**Comment by tWizT3ddreaMr** [comment]
Honestly I agree. The only thing affected would be aesthetics. If you are torn, a config boolean is a good compromise between the two. Incase a lot of people liked that.
