### ISSUE TITLE
NullpointerException

### ISSUE THREAD

**Issue by martijnpu** [snowgears/shopbugs#118]
**Describe the bug**

**To Reproduce**
1. Have an old version running
2. Update to the new version
3. Not all shops will load in succesfully
4. Lots of playershops are missing (Files, but also some shops of curtain players. See attatchement)
5. See error

**Screenshots**
https://prnt.sc/u5mzr9

**Version:**
 - Paper: git-Paper-135 (1.16.1)
 - Shop version 1.8.2

**Additional context**
https://pastebin.com/9iRL87j1
Data before and after:
[Data.zip](https://github.com/snowgears/shopbugs/files/5124368/Data.zip)

**Comment by snowgears** [comment]
Same as #127 . Fixed in 1.8.2.1
