### ISSUE TITLE
plugin not shutting down async tasks correctly

### ISSUE THREAD

**Issue by GonzoHow** [snowgears/shopbugs#119]
When running paper-144 the following error appears when shutting down the server:
This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

**To Reproduce**
Go into the servers console type "stop" and press enter.

**Version:**
 - Paper-144
 - Shop version 1.8.2

**Comment by snowgears** [comment]
Please reopen if this happens again
