### ISSUE TITLE
[Feature] clean up outdated/orphaned shop data

### ISSUE THREAD

**Issue by zedwick** [snowgears/shopbugs#12]
If player data already exists for a location, it can interfere with shops later created at the same location. I would like to see a way for this data to be removed if the shop at the corresponding location no longer exist. Either automatically as detected (on shop creation?) or via a command ran by an operator when there is known old data.

This is particularly needed when the shop plugin has been disabled for a period of time, and old shop signs removed in that same period. In my case, I had removed the shop plugin when upgrading to 1.13 as a 1.13-compatible version had not yet release. I now have a lot of orphaned shop data as players had removed the non-functional shop chests, whilst the plugin was not available.

**Comment by SiuanSong** [comment]
Similarly, when a player changes their username, the plugin will create duplicate shop files for each username, causing old signs at the same location to override new signs.  Not sure if it's planned, but perhaps storing userdata by UUID would help fix that.

**Comment by snowgears** [comment]
This should be fixed in Shop 1.8.2. Please reopen a ticket if the issue persists.
