### ISSUE TITLE
Can't create shops with barrels anymore, I want it back (because I could before the 1.16 update of this plugin)

### ISSUE THREAD

**Issue by XxMissGueraxX** [snowgears/shopbugs#120]
Hello,

Decribe problem:
I installed the newest update of this shop plugin (1.8.2), but when I checked all the shops we have on the server, the ones with barrels were broken. When I was trying to make a new shop with a barrel, I saw that it doesn't work anymore. But before the update it worked.

Solution I'd like:
I would like to see that option to make shops with barrels back in this plugin. Because most of the players on my server likes to use barrels. Is there a reason that barrels can't be used anymore? Or did I do something wrong? And is it possible to get it back in this plugin?

Version mc server/plugin:
paperspigot 1.16.1
Shop plugin 1.8.2

I'd like to hear from you.

**Comment by snowgears** [comment]
This is fixed in version 1.8.2.1 (still in development)
