### ISSUE TITLE
1.16.2 seems to break the shop plugin

### ISSUE THREAD

**Issue by Dankbudbaker** [snowgears/shopbugs#121]
So after the server updated to papermc #141 which is 1.16.2 the shop stopped working.  this is what the console says: 

 ERROR Error occurred while enabling Shop v1.8.2 (Is it up to date?)
27.08 00:31:45 [Server] INFO java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.barrier
27.08 00:31:45 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_211]
27.08 00:31:45 [Server] INFO at org.bukkit.Material.valueOf(Material.java:89) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at com.snowgears.shop.handler.ShopGuiHandler.loadIconsAndTitles(ShopGuiHandler.java:226) ~[?:?]
27.08 00:31:45 [Server] INFO at com.snowgears.shop.handler.ShopGuiHandler.<init>(ShopGuiHandler.java:46) ~[?:?]
27.08 00:31:45 [Server] INFO at com.snowgears.shop.Shop.onEnable(Shop.java:244) ~[?:?]
27.08 00:31:45 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-141]
27.08 00:31:45 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
27.08 00:31:45 [Server] INFO Disabling Shop v1.8.2

**Comment by BillyGalbreath** [comment]
You didn't follow instructions. Go read the update information again ;)

**Comment by snowgears** [comment]
Remove the guiConfig.yml file and allow a new one to generate.
