### ISSUE TITLE
WorldGuard check canUseShop error

### ISSUE THREAD

**Issue by Westloch** [snowgears/shopbugs#124]
**Describe the bug**
after a shop is created, when a player clicks on the chest to try and buy the item nothing happens ingame

**To Reproduce**
1. create sell shop
2. have a player attempt to buy item
3. nothing happens ingame
4. See error in console: https://hastebin.com/ihovodomel.sql

**Version:**
 - Paper rversion: 1.16.2
 - Shop version: 1.8.2

**Additional context**

**Comment by snowgears** [comment]
Should be fixed in 1.8.2.1. Please reopen if this issue comes up again on the newer version.
