### ISSUE TITLE
Combo shop not working properly

### ISSUE THREAD

**Issue by Nightik** [snowgears/shopbugs#126]
**Describe the bug**
Somehow cannot set combo shop. Sign updates when is clicked with desired material, but after that buying or selling doesnt work. I have found that shops with combo type doesnt work when chest and sign is facing NORTH. Other directions is just fine and work, only north direction is no good. Other directions are working fine.

**To Reproduce**
Build chest facing north direction.
Place a sign and create combo shop. Doesnt matter if admin or player.
Sign is transformed into shop sign with correct formatting, but clicking on sign results in error in console (attached bellow) and non function.

**Version:**
 - git-Spigot-b5a13e6-00bff02 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
 - Shop version [1.8.2]

**Additional context**
https://pastebin.com/tq4C2kC9

**Comment by snowgears** [comment]
Similar to #127 . Fixed in 1.8.2.1
