### ISSUE TITLE
Plugin Completely Broken

### ISSUE THREAD

**Issue by Relaxing9** [snowgears/shopbugs#127]
**Describe the bug**
Plugin not working, commands erroring out, totally not production build. Had to downgrade to 1.8.1 for my shops to work and to not get any errors on command execution

**To Reproduce**
1. Update to Shops 1.8.2 [following dev's instructions on what to reconfigure]
2. Update to 1.16.2 latest build git-Spigot-b5a13e6-927200a
3. Startup error + any command performed throws an error

**Expected behavior**
A working plugin

**Logs**
[https://pastebin.com/0vbatLD5](https://pastebin.com/0vbatLD5)
[https://pastebin.com/HUn58rSd](https://pastebin.com/HUn58rSd)

**Version:**
 - Spigot version: 1.16.2 git-Spigot-b5a13e6-927200a
 - Shop version: 1.8.2

**Comment by Relaxing9** [comment]
I'm also willing to privately send my Shop files the 1.8.1 files and you can update it yourself...

**Comment by Relaxing9** [comment]
https://www.spigotmc.org/threads/shop-a-simple-intuitive-shop-plugin-paid.79064/page-145#post-3935491

**Comment by snowgears** [comment]
Fixed in 1.8.2.1

**Comment by martijnpu** [comment]
When will this update be published?
