### ISSUE TITLE
Automatically set DisplayType to 'None' if there is no space above the chest

### ISSUE THREAD

**Issue by PotatoIQ** [snowgears/shopbugs#130]
**Is your feature request related to a problem? Please describe.**
I can't create a shop with another chest on top of it. Instead of displaying the message there's no space for the hologram to display, it should create the shop without a hologram instead if another shop is on top of it.

Here is a photo of the issue I'm facing.
https://i.imgur.com/wgANOAC.png

**Comment by snowgears** [comment]
If you set the dislpayType to "None" in the config.yml, Shops should not require a space above the chest.
For all other shops you do want displays on, you can rotate the displays to be of a different type than "None" by clicking their sign as the creator (or shift click the sign if it is an admin shop)

**Comment by snowgears** [comment]
I do like the feature request to automatically set the shop to a "None" display type if there is no space above the chest though.

**Comment by snowgears** [comment]
Added in 1.8.2.2 (still in development).

Added **forceDisplayToNoneIfBlocked** variable to main config. Default value in true
