### ISSUE TITLE
Double Chest Shops allow only one sign.

### ISSUE THREAD

**Issue by TechnoRunner18** [snowgears/shopbugs#133]
**Describe the bug**
I am trying to use each side of a double chest as its own shop. The plugin will not let me place a sign if the double chest is already being used as a shop.

**To Reproduce**
1. Place double chest.
2. Create shop with double chest (any type)
3. Attempt to place sign on other side of double chest.
Result: Plugin will deny placement of sign. 

**Expected behavior**
Sign is placed on other side of double chest to allow shop creation (like normal vanilla behaivor).

**Screenshots**
   N/A

**Version:**
 - Spigot version: [Paper-Spigot #184 for MC 1.16.2]
 - Shop version [1.8.2.1]

**Additional context**
In past versions, this used to be a normal feature.

**Comment by snowgears** [comment]
Fixed in 1.8.2.2 (still in development)
