### ISSUE TITLE
Does this plugin supports NBT tags?

### ISSUE THREAD

**Issue by TetraTheta** [snowgears/shopbugs#134]
There are so much things you can do about NBT tags. You can set item name, its lore, damage, repair cost etc.  
I use [mcstacker](https://mcstacker.net/) to define custom item. And I wonder this plugin supports these NBT tags.

![IMG1599496337](https://user-images.githubusercontent.com/37061801/92406619-6e29fd00-f173-11ea-856a-9bd69df986bd.png)

If this plugin supports all of these things, There would be so much thing I can do with this plugin.  
Even if this plugin don't support these thing, I think this plugin is still charming for me.

**Comment by snowgears** [comment]
Yep the plugin supports these!
