### ISSUE TITLE
Sales item doesn't accept lore item after server restart 

### ISSUE THREAD

**Issue by WolverStones** [snowgears/shopbugs#136]
**Describe the bug**
After create store with item with lore and restarting server shop does't not accepting item

**To Reproduce**
1. Create a shop with an item with lore
2. Restart server 
4. See bug

**Version:**
 - Spigot version:  git-Paper-185 (MC: 1.16.2)
 - Shop version 1.8.2.1

**Comment by snowgears** [comment]
Just tested this specifically with CreateReloaded key item. Shut down server and started back up. Shop still sells correct key item and cratereloaded still accepts the sold item from the shop. Please try this with regular spigot and reopen if it still does not work.
