### ISSUE TITLE
New event/shareable shops

### ISSUE THREAD

**Issue by tWizT3ddreaMr** [snowgears/shopbugs#138]
**Is your feature request related to a problem? Please describe.**
A old bug where shops made on a barrel anyone who had chest access could open. 

**Describe the solution you'd like**
An event for when the non shop owner tries to open the chest that allows play and chest location, or maybe make it where we can swap the outcome from item info to chest open.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by snowgears** [comment]
This can already be done by listening in on PlayerInteractEvent. If the clicked block is a shop chest or shop sign, cancel the event and do whatever you want in place of that
