### ISSUE TITLE
Separate Combo Shop Buy/Sell Placeholdets

### ISSUE THREAD

**Issue by Plum1111** [snowgears/shopbugs#142]
Currently the buy/sell amounts on the combo shop are in one placeholder called [priceCombo]. This can be frustrating if you want to change the layout of this such as putting it them on different lines, having different separators other than a '/', etc.

It would be nice to be able to separate them into two different placeholders like [sellPrice] and [buyPrice]. Those are just example names and could be anything else that may fit. I think this would greatly help the 'fully customizable' aspect of the plugin!

**Comment by snowgears** [comment]
This is already possible with [price] and [priceSell] tags.
[price] is the buying price and [priceSell] is the selling price
