### ISSUE TITLE
Combo Shops sell price multiplying by itself

### ISSUE THREAD

**Issue by Plum1111** [snowgears/shopbugs#143]
**Describe the bug**
The sell price is multiplied by itself upon creation. For example if it was 3, it would turn to 9 or if it was 2 it would be 4.

**To Reproduce**
1. Create a combo shop.
2. See the sell price has multiplied by itself.

**Expected behavior**
It is expected to be the same price as what was put down on the sign.

**Version:**
 - Tuinity 1.16.3-R0.1-SNAPSHOT
 - Shop version 1.8.2.2

**Comment by Nightik** [comment]
Yes, I have encountered this bug as well. Putting combo price 6/12 results into 6/144 after creation of shop.

**Comment by Alreadymelting** [comment]
Im having this happen to me aswell

**Comment by Nightik** [comment]
Could we have for this issue some hotfix? I can imagine this should be fairly quick to fix, since it seems there is some mistype while parsing the value? This is realy confusing for players and hurts shops a lot. Thanks!

**Comment by snowgears** [comment]
I will release a fix this week!

**Comment by snowgears** [comment]
Fixed in 1.8.2.3 (in progress)
