### ISSUE TITLE
PersistentDataContainer not serialized in ItemMeta

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#144]
Plugins that utilize PersistentDataContainer for ItemMeta for custom itemstacks do not work in Shops after getting serialized.

example: https://www.spigotmc.org/resources/%E2%9A%A1-goldencrates-%E2%9C%A8-advanced-custom-crates-1-14-1-16.48732/

`.     ItemStack icon = new ItemStack(Material.CHEST);
        ItemMeta meta = icon.getItemMeta();
        meta.setDisplayName("Sample Item");
       
        NamespacedKey key = new NamespacedKey(plugin, "sample_key");
        PersistentDataContainer container = meta.getPersistentDataContainer();
        container.set(key, PersistentDataType.STRING, "value");
       
        icon.setItemMeta(meta);`

The itemstacks do not throw errors but they do not stack correctly with existing plugin itemstacks because the MetaData is missing the NamedSpaceKeys

**Comment by snowgears** [comment]
@SiuanSong can you please post the file block for the shop that holds the GoldenKey item? (This is located in the Data folder and will be under "YOUR_UUID.yml" file

**Comment by SiuanSong** [comment]
https://pastebin.com/RTMa7230

**Comment by snowgears** [comment]
So the issue doesn’t appear to be the value not getting serialized as I see it right there. I will message the developer and see what’s up again.

**Comment by snowgears** [comment]
Looks to be similar to #161 and an issue with Spigot item serialization. Will close for now, but will reopen if the Spigot update containing the fix does not actually fix the issue.

**Comment by SiuanSong** [comment]
I've looked at that issue and, yes, that's exactly what happens for us.  Thanks to the update!
