### ISSUE TITLE
Lagg by Shops when reloading/starting server

### ISSUE THREAD

**Issue by martijnpu** [snowgears/shopbugs#145]
**Describe the bug**
There is a big laggspake at the moment Shops is loaded. This means starting server or /reload. The console already sends a warning of that the server can't keep up. This has something to do with the errors it shows (see pastebin).

**To Reproduce**
1. Let players make shops
2. Server is updated from pre-1.16
3. Errors showing up

**Expected behavior**
Somehere goes something wrong with loading some shops.

**Screenshots**
https://pastebin.com/iSYviVzM

**Version:**
 - Spigot version: 1.16.1 Paper (latest)
 - Shop version: 1.8.2.2

**Comment by snowgears** [comment]
This is an issue with Paper, not Shop. 

https://github.com/PaperMC/Paper/issues/2891
