### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by J4im3x0** [snowgears/shopbugs#147]
Hello! Is possible limit which displays players can use? For example I just wanna allow players to use 
![image](https://user-images.githubusercontent.com/36940599/93814433-e5a76400-fc2a-11ea-9231-81cad95a32f1.png) (2nd attached image)

**Comment by snowgears** [comment]
Yes, just set the display type to ITEM in the main config file and make sure your players do not have the **shop.setdisplay** permission.
