### ISSUE TITLE
Implement a LanguageUtil library to support other languages

### ISSUE THREAD

**Issue by Akiranya** [snowgears/shopbugs#15]
Feature request: searching for items with players own language

Say, players can search for items with chinese or japanese instead of only English words. Well this looks a lot of work to be done but actually there is a plugin - LangUtils (more info : https://github.com/NyaaCat/LanguageUtils) which offers the ability to get the name of vanilla items, entities, enchantments, and enchantment levels for plugin developers, meaning easier to localize the shop plugin for developers :D

This feature is gonna be useful and helpful because players could just type the names of what they want to buy, sell, or barter, saving tons of efforts to looking through the lists of items with GUI...especially when the server gets more and more players owning shops...

Really appreciated if this could be done!

**Comment by Akiranya** [comment]
btw one thing I want to mention is that the advantage of 'real shop' plugin is that players could open **relistic** shops, say building a supermarket with a lots of items to sell, which is cool. And what I mean by 'real shops' is players need materials to create shops (so virtual shops mean players don't need to).

The disadvantage of real shops is that real shops are geographically isolated! Other players have no idea if a player has opened a new shop in his/her home, unless the player says that to others. You've done a good job to allow players to teleport to shops but if you could implement the new feature I mentioned above that would be great...!

**Comment by Akiranya** [comment]
And can yo u add support for Towny? For example, players can only create shops within [shop plots] of their towns. I know shop plugin has been able to control players can only create shops within worldguard regions with shop flag. And this would great if shop could control that against Towny!

**Comment by snowgears** [comment]
Added support to use Localized language names in 1.8.3

**Comment by snowgears** [comment]
I am getting reports the current system of using ItemMeta.setLocale() is not particularly useful. I already use NMS in classes for client side item displays so I may just implement this for item names going forward - https://www.spigotmc.org/threads/item-localized-name.534043/

**Comment by snowgears** [comment]
https://www.spigotmc.org/threads/get-vanilla-item-name.521037/

**Comment by snowgears** [comment]
After much testing down this path, I am tabling this for now. I wrote a method that can translate any item into the clients language but requires the use of too many chat components and I dont think the end result is worth the cost of implementing this. May revisit later.
