### ISSUE TITLE
Enderchest do not work as shops

### ISSUE THREAD

**Issue by Nightik** [snowgears/shopbugs#151]
Describe the bug
With latest version 1.8.2.2 Enderchests cannot be used as shops even if enabled in config.

To Reproduce

    Enable Enderchest shops in config.yml
    Place Enderchest
    Create any type of shop with sign on it
    Plugin wont register and sign wont transform into shop sign

Expected behavior
It is expected with Enderchest shops enabled in config to be working.

Version:

    Spigot-17d78db-f8d4da0 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
    Shop version 1.8.2.2

**Comment by snowgears** [comment]
Fixed in 1.8.2.3 (in progress)
