### ISSUE TITLE
Better descriptions to show player how to use combo shops (and all shops for that matter)

### ISSUE THREAD

**Issue by Plum1111** [snowgears/shopbugs#153]
**Is your feature request related to a problem? Please describe.**
It is hard to explain combo shops to new players

**Describe the solution you'd like**
Right click to purchase something and left click to sell something (from the customer perspective)

**Optional additional feature**
It could also be a feature for buy shops (sell from the customer perspective) but that's sort of optional

**Comment by snowgears** [comment]
Also add updated gif on main page on using a combo shop

**Comment by snowgears** [comment]
This is now possible through a totally configurable name tag system to show above displays
https://media1.giphy.com/media/SoRgV6vNgAr9Kq1ZrN/giphy.gif
