### ISSUE TITLE
1.7.3.2 leftover print statements spamming console (MC 1.8)

### ISSUE THREAD

**Issue by elmaslarry** [snowgears/shopbugs#155]
Hi i am using shop and i get hard spam in the console

![Screenshot_2](https://user-images.githubusercontent.com/49719896/95588358-9e4f0f00-0a43-11eb-9290-464ac32621ab.png)

its so uncomfortable, we cant type or do nothing in console with that constant spam

How can fix?

+info: i am using paperspigot 1.8.8 and 1.12.2

**Comment by snowgears** [comment]
yeah, these were old print statements that I cleaned up in future versions of Shop. What version of Shop are you using?

**Comment by elmaslarry** [comment]
i am using 1.7.3.2
because my servers are 1.8.8 and 1.12.2 you recommend me to use that version of the plugin

**Comment by elmaslarry** [comment]
.-.

**Comment by snowgears** [comment]
I can release a patch for this version this week. I will be releasing a fix for the 1.16 version but will send you a rebuilt 1.7.3.2 file without this spam later this week

**Comment by elmaslarry** [comment]
Okey 

Through what way will you send me the plugin?

**Comment by snowgears** [comment]
Please message me on Spigot and I will send it to you there

**Comment by elmaslarry** [comment]
Okey

**Comment by elmaslarry** [comment]
done
i am PROMETEOLEGEND

**Comment by elmaslarry** [comment]
could you send me ?

**Comment by snowgears** [comment]
Yeah I will get this done this week, I have a busy week at work and this is not currently breaking any functionality. But I understand it is an annoyance and will make a file and send it this week.

**Comment by elmaslarry** [comment]
Okey Thanks!

**Comment by elmaslarry** [comment]
please send me the version

**Comment by elmaslarry** [comment]
please!!!!!!!!!!!!!

**Comment by snowgears** [comment]
sent on spigot
