### ISSUE TITLE
Add new itemframe displaytype with configurable options

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#156]
So i found out a while back that itemframes can be positioned really weirdly as per:
https://www.youtube.com/watch?v=FljPjDczTU8

That coupled with 1.16+ itemframe mechanics that allow invisible itemframes. You may be able to do some crazy things with it :)

@LogGits

**Comment by snowgears** [comment]
Added ITEM_FRAME display type in 1.8.2.3. There will be no special effects however, as they involve teleporting the itemframe to the position of a player and would cause a lot of lag.

**Comment by LogGits** [comment]
I didn't mean constant teleporting i meant invisible item-frames that the items inside are facing the correct direction (depending on the material type)(this would typically be done once, unless they change the effect type to something else and back)
