### ISSUE TITLE
Player heads glitching on floating item above shop chest

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#157]
I am having this issue where a player head on a shop displaying above the shop chest will sometimes be a bunch of that head at one time like it duplicated. Then all of a sudden they will disappear like it changed modes without player interaction. Ill try to provide screenshots when it happens next. It seems to be random.

@fahlur

**Comment by fahlur** [comment]
was checking on the 3rd display option of it just being static and that worked flawlessly so far for the entirety of the day. put it back on the spinning head to see if I can "catch it in the "act"

**Comment by snowgears** [comment]
Should be fixed in 1.8.2.3 (in progress)

Please reopen if this issue persists.
