### ISSUE TITLE
Add feature to "buy stack" of the item being sold

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#159]
It would be really convenient to have some sort of "buy stack" with a confirmation. E.g. shift, left click to open a "buy stack" confirmation screen where the amount would be within 2-64 depending on what they can afford and how many items are left.

E.g. if it's an admin shop it'd just be 2-64 depending on how much they can afford.

This way if a shop is selling stacks of 6 dirt for example, the buy stack option would allow them to buy a stack of 60 dirt (since max is 64 but increments of 6)
@LogGits

**Comment by Kosyne** [comment]
This would be a great addition. Showcase did it via sneaking. Not sure that would conflict with the change display type function though (though I wouldn't mind the display type being a command, and the stack-buying be done through sneak-click instead).

**Comment by PotatoIQ** [comment]
> This would be a great addition. Showcase did it via sneaking. Not sure that would conflict with the change display type function though (though I wouldn't mind the display type being a command, and the stack-buying be done through sneak-click instead).

It wouldn't really confligt with the display feature, since only the owner of the shop need to sneak to change the display, while other players sneaking and clicking on the sign does nothing. The only conflict I can think of, if an admin or op click on the sign, which then u can add an option to toggle on/off admins changing chestshop signs displays

**Comment by Terminal-Access** [comment]
Would like to see this feature added, Major +1

**Comment by McSharidan** [comment]
This is a frequently requested feature in the community I'm admining. +1 from me as well

**Comment by snowgears** [comment]
Added in 1.8.3.6 (in progress)
