### ISSUE TITLE
Shorten large numbers on signs (1k=1000,1M=million, etc)

### ISSUE THREAD

**Issue by Nedjii** [snowgears/shopbugs#16]
Hello, shop is a really nice plugin but nearly unusable on op prison server as you need binocles to read a shop because there are tons of "0", so that'd be nice to have a custom money format : 1000 = 1k etc.
Almost every economy plugin has this feature,
thanks !

**Comment by Nedjii** [comment]
I realized that you couldn't even make a shop if the price is too high, that put "$" on the sign, then that's quite urgent.

**Comment by Nedjii** [comment]
Can we get source code for 1.8.8 version compatible so we make it ourself ?

**Comment by Nedjii** [comment]
UP

**Comment by Nedjii** [comment]
Up

**Comment by Nedjii** [comment]
Any update ?

**Comment by MCMBJ** [comment]
UP
we need a better momeny format: K - M - B - T -...

**Comment by Nedjii** [comment]
Nearly a year since I suggested this ...

**Comment by snowgears** [comment]
Added in 1.8.2.2 (still in development)

https://media2.giphy.com/media/kF6icXcTjSr2dS8SMj/giphy.gif
