### ISSUE TITLE
Option for show custom name above displayed item

### ISSUE THREAD

**Issue by TetraTheta** [snowgears/shopbugs#160]
### Is your feature request related to a problem? Please describe.
This is feature request, not a bug.

I use paper with custom name(ex: `Credit Coupon #01`) as check(cheque). All checks have different credit value. `#01` would have value as $100, `#02` would have value as $300 etc.
I use this plugin's 'admin buy shop' as 'exchange counter' and since shop item preview(which is floating item above chest) doesn't show item's name with it, every player must right-click every chest to find what shop does he need to deal with.

This is some kind of inconvenience I think.

### Describe the solution you'd like
When user creates shop with sign, add option for whether display its item name above item. if we use `buy admin disp` in 4th line of shop sign, item name will be visiable with floating item. 

### Describe alternatives you've considered
I don't have any good alternative. If I found any, I will add.

### Additional context
Sorry for this poor made screenshot. I made this in vanilla minecraft and this is all what I can do with it...  

![2020-10-19_16 30 22](https://user-images.githubusercontent.com/37061801/96414811-930c9800-1228-11eb-94e2-dec2a362d483.png)  
I tried with invisiable armor stand but it would be very bad idea for this plugin since it would mess up other player's vision with many item name displaying. If you must use armor stand for displaying item name, 'Only show item name(via armor stand) when a player is near shop' option would be nice solution about that problem.

Here is some example why this plugin should hide names behind wall or far from player.

![2020-10-21_03 20 26](https://user-images.githubusercontent.com/37061801/96627924-82554280-134c-11eb-827f-c721f8963699.png)  
This looks fair enough... But...  
![2020-10-21_03 20 33](https://user-images.githubusercontent.com/37061801/96627951-8da86e00-134c-11eb-99bb-e825713fe7a5.png)  
![2020-10-21_03 20 39](https://user-images.githubusercontent.com/37061801/96627964-90a35e80-134c-11eb-86ab-4ea47464800c.png)  
Now, your vision is gone messed up. You can't read any of that texts...

**Comment by snowgears** [comment]
I like this idea a lot!

**Comment by TetraTheta** [comment]
I added some screenshot of 'Why this plugin should hide names of item which is sold'. For now, I have two idea.
1. Only show name of item a player is looking at.  
If you pointing a shop, only that shop item(that you are pointing) name would be shown. But other shop(which are also selling items) won't show item names above.
2. Only show nearest shop item name  
I think this would be bad idea but this also makes sense. Only difference of condition is 'Looking at' and 'Nearest'.

**Comment by snowgears** [comment]
Added in 1.8.2.3. However, item names are currently shown at all times due to a Spigot limitation. I will revisit this at a later date to add the "only shown when looking at them" portion.
