### ISSUE TITLE
Players can move items in Shop GUI

### ISSUE THREAD

**Issue by YourRapiddeath** [snowgears/shopbugs#163]
Players can move items to the shop menu using the number keys. And don't get them out again.

**To Reproduce**
1 ) Open Shop Gui
2 ) Mouse over an empty inventory field
3 ) Press a number key 1-9 (with Item)

**Version:**
 - Server : Paper 240
 - Shop : 1.8.2.2

**Additional context**
I think by canceling **ClickType.NUMBER_KEY** should fix the problem

**Comment by snowgears** [comment]
Fixed in 1.8.2.3 (in progress)
