### ISSUE TITLE
Admin Shop to Buy From Players

### ISSUE THREAD

**Issue by Kosyne** [snowgears/shopbugs#164]
I use items for currency and allow players to go to and from that physical currency at 'exchanges'.

Typically with older plugins such as showcase, I would make an admin shop to buy 1:1, and an admin shop to sell 1:1, but I don't seem to be able to do that with this plugin.

Would be awesome if something like that could be added!

**Comment by snowgears** [comment]
There are buying shops, selling shops, barter shops, and combo shops (combing buying and selling in the same shop).

If you go into your exact use case more I should be able to point you in the right direction on how to accomplish the same thing using Shop.

**Comment by Kosyne** [comment]
So the idea is to use a physicalized currency. I use these admin-controlled kiosks to allow players to convert from economy system to physical item, and vice versa.

My setup is:
- Admin shop that buys emeralds for 100 coins AND
- Adminshop that sells emeralds for 100 coins

so players can freely go between physicalized and economy currencies.


---

Currently, this plugin only supports admin shops that buy an unlimited number of items, I've not yet found a way to create an admin shop that **buys** an unlimited number of items.

**Comment by snowgears** [comment]
You can make a buying or a selling shop admin.
Just write "admin buy" or "admin sell" on the last line.

Am I missing something?

**Comment by Kosyne** [comment]
Oh man, you are absolutely right. I remember trying something similar to this and it not working, I must have just gotten it off slightly. Thanks for pointing me in the right direction!

**Comment by snowgears** [comment]
No problem at all! Happy to help!
