### ISSUE TITLE
Shop Gui Teleport requires Permissions to be used

### ISSUE THREAD

**Issue by ghost-ryder13** [snowgears/shopbugs#165]
**Describe the bug**
Shop GUI will only teleport player if they are OP or if usePermissions is set to True and player has shop.gui.teleport

**To Reproduce**
1. Turn off "use permissions" in config
2. use /shop
3. choose shop to be teleported to
4. nothing happens

5. Turn on "use permissions" in config
6. Give perm to player
7. Use /shop
8. choose shop to be teleported to
9. Player gets teleported

**Expected behavior**
Expect to be teleported to chosen shop

**Screenshots**

**Version:**
-Paper 204 1.16.3
-Shop Vs 1.8.2.2

**Additional context**

**Comment by snowgears** [comment]
This is not a bug. This is expected behavior. Many people do not want this as a default, and if they do want to use it as the default they can give the teleport permission to all players.

**Comment by ghost-ryder13** [comment]
So, just to be clear. It is by design that the only way to use the teleport feature is to turn on "usepermissions" and give the coinciding permission?

So by design I can't implement using gui to teleport with "usepermissions" off?

**Comment by snowgears** [comment]
As of now that is correct. If enough people want teleporting to be the default, I can look into changing the default behavior though.

**Comment by ghost-ryder13** [comment]
10-4 
Thank you for clarifying!!
😄
