### ISSUE TITLE
Option to have full numbers on the signs

### ISSUE THREAD

**Issue by Plum1111** [snowgears/shopbugs#166]
**Is your feature request related to a problem? Please describe.**
Some people prefer to have the full number e.g $1500 rather than $1.50k

**Describe the solution you'd like**
I would like to suggest a config option to disable this feature

**Comment by PotatoIQ** [comment]
My players were complaining about the new format feature also, a solution could be adding an option for us to choose the formatting like some economy plugins:
Example for options:
Option1: #,### if no decimals and #,###.05 if there are decimals | ex: 56,644 & 541,984.08
Option2: #K if there are no decimals and #.50K if there are decimals | ex: 25k & 23.84K
Option3: Use option 1 by default if there is enough space for it to show in the sign line, or option 2 if the number exceeds the allowed number of characters in a single sign line

**Comment by snowgears** [comment]
Fixed in 1.8.3.6 (in progress)
