### ISSUE TITLE
Combo shop have their sell price squared

### ISSUE THREAD

**Issue by markusew** [snowgears/shopbugs#167]
**Describe the bug**
Whenever someone tries to create a combo shop the sell price they listed is squared making it near impossible to conveniently create combo shops.

**To Reproduce**
Make a combo shop and it should be apparent

**Version:**
 - Spigot version: tuinity 1.16.3
 - Shop version: 1.8.2.2

**Comment by snowgears** [comment]
Duplicate of #143
