### ISSUE TITLE
Holographics Update

### ISSUE THREAD

**Issue by TheMartyCZ** [snowgears/shopbugs#171]
- [ ] I suggest that the item be displayed either after the cursor move on the item or at a certain distance. In order to set eg 5 blocks.

- [ ] To correct the hologram display. (So ​​that he is not in item)

- [ ] Option to display enchants as a hologram

![obrázek_2020-11-06_002102](https://user-images.githubusercontent.com/45405349/98307402-f38c2b00-1fc5-11eb-8963-7070bfdd7ea1.png)

**Comment by PotatoIQ** [comment]
That would be really helpful if you the enchant of the enchanted books are displayed as text hologram above the actual holograms

**Comment by snowgears** [comment]
Fixed with a totally configurable hologram system in 1.8.2.4 (still in progress)
![giphy (4)](https://user-images.githubusercontent.com/4141199/103433719-2eb47000-4bab-11eb-9f43-262b958bbd6e.gif)

**Comment by PotatoIQ** [comment]
Woah this is amazing tysm!
