### ISSUE TITLE
Displays not getting removed correctly and duplicating

### ISSUE THREAD

**Issue by TheMartyCZ** [snowgears/shopbugs#174]
**Describe the bug**

1. After destroying the store

![image](https://user-images.githubusercontent.com/45405349/98482243-5c5ee780-2200-11eb-80a1-3ef9beb4d611.png)
![image](https://user-images.githubusercontent.com/45405349/98482272-9334fd80-2200-11eb-9891-59635b168691.png)

2.  When quickly changing the look of the shop

![image](https://user-images.githubusercontent.com/45405349/98482258-7698c580-2200-11eb-9ab7-eceab5e4010d.png)
![image](https://user-images.githubusercontent.com/45405349/98482266-844e4b00-2200-11eb-8300-2b3cba970a33.png)

**Version:**
 - Spigot version: [SSSpigot 1.16.3]
 - Shop version: [1.8.2.3]

**Comment by PotatoIQ** [comment]
same issue
Paper 1.16.4 build #264
Shop Version: 1.8.2.3

**Comment by Sherineko** [comment]
at 1.16.3, I had this problem too :)

**Comment by kev2k2de** [comment]
Same problem, items are dulplicating since 1.8.2.3

**Comment by Nightik** [comment]
Yup, confirming issue in lastest version 1.8.2.3. Could use some hotfix, a lot of floating items are drasticly reducing fps for players.

**Comment by SiuanSong** [comment]
I'd suggest just turning off the display feature entirely until this is fixed.  We don't use it at all simply because of the entities.

**Comment by markusew** [comment]
If it's any help to the dev, I can consistently reproduce this bug if I first create a shop, then unload the chunk with the shop in, go back to the shop, and rotate the display types. After 1 rotation I will get a duplicate display item.

**Comment by snowgears** [comment]
Fixed! (Update 1.8.2.4 - still in progress)

**Comment by snowgears** [comment]
Apparently this is still happening to some users in 1.8.2.4 (running **/shop item refresh** fixes the issue but the display duplicates end up happening again)

**Comment by snowgears** [comment]
I think I fixed this in 1.8.2.5 (in progress) as I have been unable to reproduce this during my personal testing. PLEASE LET ME KNOW IF THIS HAPPENS AGAIN.
