### ISSUE TITLE
Players can take menu items from /shop

### ISSUE THREAD

**Issue by SiuanSong** [snowgears/shopbugs#177]
**Describe the bug**
When using the /shop GUI, players can take the menu items out and put them in their inventory. This completely breaks the GUI even if you put the items back.  There were no errors in console and several players could do it.

**To Reproduce**
1. Open the /shop GUi
2. Click on an item and drag it out.

**Version:**
 - Paper version: Paper 1.16.3 1.16.3 #253
 - Shop version: 1.8.2.3

**Comment by snowgears** [comment]
Unable to reproduce. Please try with no other plugins installed and let me know if you are still able to reproduce this. It may be another plugin overriding this. If you are still able to please reopen the issue.
