### ISSUE TITLE
Double Chests act as single if there is a solid block above them

### ISSUE THREAD

**Issue by SiuanSong** [snowgears/shopbugs#178]
**Describe the bug**
If there is a solid block above a double shop chest, the chest acts as a single shop chest.  It will only allow 27 slots to fill before saying "shop is full."

**To Reproduce**
1. Place a double chest.
2. Place a solid block above either one side of the chest or both.
3. Add your sign. 
4. Fill up the chest until 26 slots.
5. Buy items until 27th slot is full.
6. Shop claims the chest is full.

**Expected behavior**
For double chests to always act as double chests.

**Version:**
 - Paper version: Paper 1.16.3 1.16.3 #253
 - Shop version: 1.8.2.3

**Comment by snowgears** [comment]
This appeared to be a spigot issue. Please reopen if it persists in shop version 1.8.2.5
