### ISSUE TITLE
God Armor Out of Stock Glitch

### ISSUE THREAD

**Issue by WillisAwesome** [snowgears/shopbugs#18]
When Selling Enchanted Armor people are getting an error "Shop out of stock!" but the shop is stocked with the same item how do I fix this

**Comment by WillisAwesome** [comment]
Is this going to be fixed?

**Comment by WillisAwesome** [comment]
Hello?

**Comment by snowgears** [comment]
Yes, it is in the queue. Thanks for your patience!

**Comment by WillisAwesome** [comment]
What is the ETA for the Fix?

**Comment by snowgears** [comment]
This appears to be fixed in Shop 1.8.2 with compiled Spigot 1.16 dependencies. If this is not fixed please reopen the ticket.
