### ISSUE TITLE
Nametags with Quantities 

### ISSUE THREAD

**Issue by rshuttle1337** [snowgears/shopbugs#180]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of quantity for sale/purchase is needed.

**Describe the solution you'd like**
The new nametags are great, but would it be possible to add a quantity to the end? For example, the nametag might say "Netherite Ingot x5".

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Regards,
rshuttle

**Comment by snowgears** [comment]
Bundling this with #171
