### ISSUE TITLE
Add [item enchants] placeholder, remove automatic spacing in config, and fix hoverable item placeholder

### ISSUE THREAD

**Issue by PotatoIQ** [snowgears/shopbugs#181]
**Is your feature request related to a problem? Please describe.**
1- Hoverable items placeholder doesn't show the actual color of the item [[item]] while [item] shows the actual color of the item but it is not hoverable.
2- remove automatic spacing between lines for description section in chat config file.
3- Add [item enchants] placeholder to chat configuration which displays a list of the item enchants with their levels

**Describe the solution you'd like**
1- Show the actual color of the item name when it is hoverable item [[item]] and only color the parentheses so &b[[item]] would show blue paranthes, and make the item hoverable, and show the actual color of the item
2- Remove the automatic spacing between lines for description section
3- Add new placeholder [item enchants] that displays the enchants of item in the chat for the chat config file.

**Additional context**
shop version: 1.8.2.3
https://hastebin.com/ilegokohuc.less
https://i.ibb.co/L1ddf8W/2020-11-29-20-19-26.png

**Comment by snowgears** [comment]
Also add [item lore] tag

**Comment by snowgears** [comment]
Added lore, enchantments, potion names, and whitespace fixes in 1.8.2.6 (in progress)
