### ISSUE TITLE
New way to add items and price changes

### ISSUE THREAD

**Issue by Balmys** [snowgears/shopbugs#183]
Here's a feature request or two that I think could improve the plugin! If any of these things are already in the plugin I may have just overlooked it.
1. Have a way to set an item without having to click the sign with said item. (Say you want to buy diamonds in your shop but you don't have a diamond to click the sign with. This could be a toggleable setting where you can set a line to either the item name or Minecraft ID)
2. The dollar sign for virtual currency is placed behind the amount where it would be more accurate in front of it. (Currently says ' 3.0 $ ' , should say ' $ 3.0 ')
Great plugin though! Works perfectly and has no issues on 1.16.3. Customization is great!

**Comment by snowgears** [comment]
Yep! Both of these are already in the plugin! Responses were in the spigot thread.
