### ISSUE TITLE
New Out of stock / in stock Shop Sign Change added in config

### ISSUE THREAD

**Issue by RenegadeMc** [snowgears/shopbugs#184]
**Is your feature request related to a problem? Please describe.**
It is not at all related to a problem its just a request.

**Describe the solution you'd like**
So I would like it if you could have the Signs change for when the shop is in stock / out of stock

In stock (selling) / empty (Buying)
         1: "&a[Sell]"
         2: "[amount]"
         3: "[item]"
         4: "[price]"

Out of stock (Selling) / Full (Buying)

         1: "&4[Sell]"
         2: "[amount]"
         3: "[item]"
         4: "[price]"

**Describe alternatives you've considered**
Well i really cant think of any thing else really.

**Additional context**

https://cdn.discordapp.com/attachments/745855727494758441/790626094880391209/unknown.png
https://cdn.discordapp.com/attachments/771121961535406130/790632250144063488/unknown.png

**Comment by snowgears** [comment]
Added in 1.8.2.4 (in progress)

Added new tag: [stock color]
This changes text to DARK_RED when shop has no stock
This changes text to GREEN when shop has stock
