### ISSUE TITLE
Prevent Nested Shulkers

### ISSUE THREAD

**Issue by MacTh3Mac** [snowgears/shopbugs#187]
**Describe the bug**
Using Buy Shops players are able to place shulker boxes inside shucker boxes
This enables the players to produce huge sized items, which can corrupt player or region files when placed /dropped etc

**To Reproduce**
1. Setup buy shop sign on a shulker box
2. Sell shulker boxes to the shop

**Expected behavior**
Not to be able to nest shulker boxes

**Version:**
 - Spigot version: Paper 1.12.2, Paper 1.16.4
 - Shop version: All

**Additional context**

If you wish to keep this behaviour please at least make it toggleable as you do with enderchests.

**Comment by snowgears** [comment]
Fixed in 1.8.2.5 (in progress)
