### ISSUE TITLE
Display Tag Glitching

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#188]
Some users are experiencing display tag glitching like in gif below:

![glitch_gif](https://media2.giphy.com/media/EAvcyVFrHMfJ2Jio4m/giphy.gif)

This seems to be an issue with Paper. I have been unable to reproduce myself on Spigot so far.

**Comment by DitDitGitHub** [comment]
I’m having this issue :/

**Comment by Managering** [comment]
I'm also experiencing this issue. I've tried setting the displays to "" but now I am getting an armor stand still popping up. Is there a way to disable them all together until a fix is presented?
https://imgur.com/a/xEZQXld

**Comment by snowgears** [comment]
You can set the string to " " instead of "" if you want it to not show. But I would recommend setting the display tags to 'OFF' in the main config.yml rather than VIEW_SIGN (note: 'OFF' instead of OFF)

**Comment by Mattrolol** [comment]
> You can set the string to " " instead of "" if you want it to not show. But I would recommend setting the display tags to 'OFF' in the main config.yml rather than VIEW_SIGN (note: 'OFF' instead of OFF)

I tried that it wouldn't work :disappointed:

**Comment by snowgears** [comment]
This should be fixed in 1.8.2.5 (in progress). Please reopen if the issue persists
