### ISSUE TITLE
Item Duplication Dupe (during transactions)

### ISSUE THREAD

**Issue by AnonymousOG** [snowgears/shopbugs#189]
**Describe the bug**
This bug requires 2 people, but allows you to duplicate items using the shop plugin. 

**To Reproduce**
To reproduce: you’ll need 2 accounts (preferably 2 monitors or 2 laptops so you can get the timing right)
1. Set up a chest shop at any price selling virtually anything
2. Player A will be appointed to opening the chest whilst player B is right clicking the shop chest to purchase the item.
3. At the EXACT same time Player A needs to remove the item from the chest while Player B right clicks the sign to purchase the item.
4. The item will now be duplicated as 1 item in each inventory. This works about 80% of the time so long as you have the timing correct.
Note step 1: This only works when selling an item from a shop chest

**Expected behavior**
Expected the item to just be transferred from one player to another and not duplicate

**Screenshots**
Videos:
https://www.youtube.com/watch?v=9NbjXI9W1Xo&feature=youtu.be

**Version:**
 - Spigot version: Paper spigot 1.12.2
 - Shop version: version: 1.7.3.2

**Additional context**
N/A

**Comment by snowgears** [comment]
Thanks for reporting this! This is a great edge case that has never been reported.

**Comment by AnonymousOG** [comment]
> Thanks for reporting this! This is a great edge case that has never been reported.

Do you have any ideas when this can be fixed? I've had to remove the plugin for the time being.

**Comment by AnonymousOG** [comment]
Hi, just wanted to follow up again and ask if you need anymore information in order to get this bug fixed? Chest shops were a pretty important feature on our server and unfortunately, we had to disable the plugin due to this bug.

**Comment by snowgears** [comment]
Nope, that info provided was perfect. I will be fixing this in the next update but no eta at the moment.

**Comment by AnonymousOG** [comment]
Alright

**Comment by AnonymousOG** [comment]
Hi sorry to bother but players are asking for this feature back and it is not like we can migrate chest shop plugins for the time being due to the userdata. Do you know when I expect this to be fixed or whenever the next update is coming out?

**Comment by snowgears** [comment]
Planning on an update very soon here (hopefully within 2 weeks, maybe sooner if I can)

**Comment by snowgears** [comment]
Fixed in 1.8.2.5 (in progress)
