### ISSUE TITLE
Combo Shops buy/sell switch sides depending the pitch of the user.

### ISSUE THREAD

**Issue by markusew** [snowgears/shopbugs#191]
**Describe the bug**
If you make a combo shop, you expect the left side to be buy, and the right side to be sell. However, if the players pitch is negative (looking up) these two switch side and suddenly the left side is to sell, and the right side is to buy. 

**To Reproduce**
1. Make a combo chest.
2. Test the shop with looking down at the sign.
3. Test the shop while looking up at the sign

**Expected behavior**
If you look up at a chest, the sides switch with each other. 

**Screenshots**
https://i.imgur.com/AMoPdvx.png
https://i.imgur.com/v7wiSdM.png

**Version:**
 - Spigot version: Paper Tuinity 1.16.4
 - Shop version: 1.8.2.4

**Comment by snowgears** [comment]
Thanks for reporting this!

**Comment by snowgears** [comment]
Fixed in 1.8.2.5 (in progress)
