### ISSUE TITLE
Shop protection not active if put on side

### ISSUE THREAD

**Issue by tWizT3ddreaMr** [snowgears/shopbugs#192]
**Describe the bug**
If you put the shop sign on the side of the chest, any player can open the chest

**To Reproduce**
1. Make a shop on the side of either Double or single Chest
2. Have an alt/another user try to open, and it will

**Expected behavior**
Is supposed to stop them from opening and give them info on the shop

**Screenshots**

https://user-images.githubusercontent.com/9572910/104974379-6b5ed480-59bd-11eb-98d8-b4569267b105.mp4

**Version:**
 - Spigot version: [paper 1.16.4]
 - Shop version: [1.8.2.4]

**Additional context**
I had no additional plugins on the server for my reproduction. Also default config. Was a fresh install with a new plugin folder
Also you can have multiple shops, though I am not sure if that is not an intended feature.

**Comment by snowgears** [comment]
Fixed in 1.8.2.5 (in progress)
