### ISSUE TITLE
Back button in GUI editor uneditable

### ISSUE THREAD

**Issue by Plum1111** [snowgears/shopbugs#193]
**Describe the bug**
Back button in GUI editor isn't editable

**To Reproduce**
1. Edit the back button

**Expected behavior**
The back button changes when edited

**Screenshots**

**Version:**
 - Spigot version: Paper 1.16.4
 - Shop version: 1.8.2.4

**Comment by snowgears** [comment]
Fixed in 1.8.3 (in progress)
