### ISSUE TITLE
Shop GUI notifications don't line up with the state when changed via command

### ISSUE THREAD

**Issue by Plum1111** [snowgears/shopbugs#194]
**Describe the bug**
The Shop GUI notifications state doesn't line up with the state when changed via command. e.g. If I had user notifs enabled by using the gui, then did command /shop notify user which changed it to false, it would still say it was enabled in the gui when it actually isn't

**To Reproduce**
1. Login
2. Look at the notification state for user (probably enabled)
3. do /shop notify user
4. See if the notification state for user is still enabled (probably still enabled)
(ofc this works for all of the states)

**Expected behavior**
GUI changes when the command state is changed

**Version:**
 - Spigot version: Paper 1.16.4
 - Shop version: 1.8.2.4

**Comment by snowgears** [comment]
Fixed in 1.8.3 (in progress)
