### ISSUE TITLE
Permission for an extra amount of chestshops

### ISSUE THREAD

**Issue by Managering** [snowgears/shopbugs#197]
Hi would it be possible to create a permission that allows an extra amount of chestshops? 

We'd like to make it possible for someone to have the permission for 50 chestshops
And then they can get shop.buildlimit.extra.#
Which will allow them to get 25 extra for example. 

That way we can put vouchers for extra shops in vote crates for example.

**Comment by snowgears** [comment]
Added in 1.8.4 (in progress)
