### ISSUE TITLE
Item Frames get frozen and are unbreakable after shop is deleted

### ISSUE THREAD

**Issue by MrGreenGem** [snowgears/shopbugs#198]
**Describe the bug**
When I place an item frame behind an itemframe display on a chest shop and delete the chest shop that has item frames as the display type the item frames get stuck on the wall and cannot be deleted. 

**To Reproduce**
Create a chest shop and select itemframe as display.
Try placing an item frame on the block behind it. 
Destroy the chest shop and the item frame is frozen behind it and cannot be deleted. 

**Expected behavior**
I expect to be able to remove the item frame behind the chest shop I created even if the plugin already creates an item frame. 
If a player accidentally puts an item frame on the back of the wall or has one from a previous display type but then decides they want to switch to item frame it bugs out and overlaps them and "locks" the item frame so I can't break it. This makes it permanent and can be frustration, as you might imagine. 

**Screenshots**

**Version:**
 - PaperSpigot 1.16.5 Build #466
 - Shop version: 1.8.2.4

**Additional context**
I love this plugin and I hope that this minor irritation can be fixed. Thank you for your time :)

**Comment by snowgears** [comment]
Fixed in 1.8.2.5 (in progress)
