### ISSUE TITLE
Item above the shop the item keeps disapearing!!

### ISSUE THREAD

**Issue by MrFoxzer** [snowgears/shopbugs#199]
displayCycle:
   - ITEM

this is my config and after a while they just disappear randomly

**Comment by Firestone82** [comment]
Hi, works normally for me. Do you have any item cleaner plugin on your server? If yes, it need to be hooked into shop plugin, to check if that entity is shop item display.

**Comment by MrFoxzer** [comment]
ah okay, I use clear lag, im not sure how to hook them together

**Comment by snowgears** [comment]
CleagLagg is no longer supported. This has been talked about fairly extensively in the discord multiple times but a quick summary of the fix is to remove clearlagg. https://discordapp.com/channels/745855281422008361/745855727494758441/804915316780957725
