### ISSUE TITLE
Stacking of non stack-able items

### ISSUE THREAD

**Issue by Alanaaya** [snowgears/shopbugs#2]
This plugin gives you a lot of features and flexibility.

However, it doesn't support stacking of non stack-able items in the shop inventory. This gives
players a hard time since the shop inventory floods, making them lose sales.

I would like and love a stacking feature.

This would be able to stack items like:
1. Saddle(s)
2. Cake(s)
3. Horse Armor
4. Music disc(s)
5. Different kinds of stew
6. Water, Lava and Milk bucket(s)

Either way, I appreciate the effort of the developer. This is
a must-have for any production server.

**Comment by snowgears** [comment]
This will not be fixed as I want to remain "authentic" to the Minecraft chest
