### ISSUE TITLE
Add support for GeyserMC bedrock clients

### ISSUE THREAD

**Issue by coolty** [snowgears/shopbugs#203]
**Describe the bug**
When bedrock players attempt to make a [shop] sign, it always says "Line 2 must be a positive number!"

**To Reproduce**
1. Log on with bedrock using geyser to a java server running this plugin
2. try to make a shop sign
3. ???
4. Error!

**Expected behavior**
The shop to be created.

**Version:**
 - Spigot version: git-Tuinity-"f8c0db4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - Shop version: 1.8.2.4

**Comment by coolty** [comment]
any update on this?

**Comment by snowgears** [comment]
According to a review on 1.8.3.1, it appears this has been fixed.
https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/reviews?resource_rating_id=383852

Please reopen if it does not work going forward.
