### ISSUE TITLE
Item duplication 

### ISSUE THREAD

**Issue by WolverStones** [snowgears/shopbugs#204]
**I found a way to duplicate an item when I buy it **
https://www.youtube.com/watch?v=EynHI5LYoyE

This is an enchant books from the plugin 
https://www.spigotmc.org/resources/⭕-advancedenchantments-⭐create-custom-enchants-1-16-5-⭐-200-enchants-✅-30-sale.43058/updates

**To Reproduce**
More in video..

**Version:**
 - Spigot version: Paper 519 1.16.5
 - Shop version: 1.8.2.4

**Comment by snowgears** [comment]
Tested and confirmed to be a priority bug in AdvancedEnchantments. Reported the bug to them here: https://github.com/GC-spigot/AdvancedEnchantments/issues/1988

Please reopen if this persists once they patch that

**Comment by WolverStones** [comment]
https://youtu.be/DNkujz_ueYE

I tried it and it looks like the problem persists

**Comment by WolverStones** [comment]
maybe it wouldn't be bad to add a blacklist or somehow make the specific item not add to the shop.

**Comment by snowgears** [comment]
Fixed in 1.8.2.6 (in progress).

Confirmed the fix on a server that was experiencing this before with over 1000 shops.

**Comment by snowgears** [comment]
#31

**Comment by snowgears** [comment]
Tested and confirmed to still be a priority bug in AdvancedEnchantments. Responded again to the bug here: GC-spigot/AdvancedEnchantments#1988
