### ISSUE TITLE
Some users not seeing one item in barter shop

### ISSUE THREAD

**Issue by DJIronic** [snowgears/shopbugs#206]
**Describe the bug**
Shops are not showing both trade items from time to time. I was unable to find the patter, you will just walk back to the shop  after leaving and you will not see the item.

We tried disabling shaders and resource packs, no help. Also some users can see the item, but some of them can't (at the same time)

**To Reproduce**
1. Make a barter tradeshop
2. Go away, play minecraft
3. come back
4. realise that that you dont know what is the shop wanting to barter, only the thing user is willing to give

**Expected behavior**
Store should show both items of the trade.

**Screenshots**

![image](https://user-images.githubusercontent.com/9658012/110217652-8aee8580-7eb5-11eb-905b-d97d2fb160c1.png)

**Version:**
 - 1.16.5
 - 1.8.2.4

**Additional context**
It is random, the shop was here for days, I came back..and no issue, today we came back to test new shops...and one of them is missing for some of us.

**Comment by DJIronic** [comment]
Here is how it should look (after relog in this case):
![image](https://user-images.githubusercontent.com/9658012/110218697-672e3e00-7ebb-11eb-8504-17179a9d099c.png)

**Comment by snowgears** [comment]
Is everyone using the default Java edition Minecraft client?

**Comment by DJIronic** [comment]
Yes, max OptiFine, but thats ultra common, so we must count it as Java edition client.

**Comment by DJIronic** [comment]
Any idea how to fix this?

**Comment by snowgears** [comment]
If some players are seeing it and others are not, it is a server/client issue and not a plugin issue. I will continue to do some testing to confirm though.
