### ISSUE TITLE
bug instalation

### ISSUE THREAD

**Issue by stiruzo** [snowgears/shopbugs#21]
Hi, I just installed the plugin but it does not work. when i do / shop it says "an internal error occurred ..." and the plugin folder does not create it :( can you help me please

**Comment by snowgears** [comment]
Are you using paper spigot or regular spigot? What version of spigot and what version of the plugin are you running?

**Comment by stiruzo** [comment]
I do not understand?

**Comment by stiruzo** [comment]
spigot 1.11.2, le plugin et Shop - un plugin boutique simple et intuitif fr 1.8.0.1

**Comment by stiruzo** [comment]
spigot 1.11.2, the plugin and Shop - a simple and intuitive shop plugin en 1.8.0.1

**Comment by snowgears** [comment]
For all spigot versions under 1.13 please use a shop version below 1.8

**Comment by stiruzo** [comment]
Hey, how to allow the player to create a shop that sells resources for cash in a given area. and that they can not make shop other than in this area? thank you

**Comment by untuned** [comment]
> 
> 
> Hey, how to allow the player to create a shop that sells resources for cash in a given area. and that they can not make shop other than in this area? thank you

You can use WorldGuard with the `shop` flag for that by setting `hookWorldGuard` in the config.yml to true.  However, this will make ALL shops need to be in a region with the `shop` flag.

**Comment by snowgears** [comment]
duplicate of issue #11 . Solved.
