### ISSUE TITLE
Creative limitation bypass

### ISSUE THREAD

**Issue by DJIronic** [snowgears/shopbugs#210]
**Describe the bug**
Player can escape from the limited creative mode by re-connecting when in selection. They will get back with unlimited creative mode.

**To Reproduce**
1. create shop
2. enter creative selection
3. disconnect
4. connect back
5. enjoy creative

**Expected behavior**
Creative mode should be clossed.

**Version:**
 - Spigot version: 1.16.5
 - Shop version: latest

**Additional context**
There is a workaround by enabling the "force gamemode" feature, so every player will get survival no matter what they had when disconnected. That will fix this issue, but also bring issues for admins using primarly GM3 as they can loging back stuck in a wall.

**Comment by snowgears** [comment]
Fixed in 1.8.2.5 (in progress)

Please reopen this if it happens again in the future
