### ISSUE TITLE
MMO Items hook

### ISSUE THREAD

**Issue by NiDEV-Tech** [snowgears/shopbugs#211]
**Is your feature request related to a problem? Please describe.**
I use this plugin for basic gamble, but the problem is the function with hook
in to MMO Items plugin. I have many custom items which i need get to player
only from classic shop but with gamble they can get it. 

Example : I have item which is only for event but they can now win in gamble.

**Describe the solution you'd like**
Put in config choice to blacklisted some items from gamble, But the custom
items have basic in classic items so i dont know how to do it easily.

Example : 

MMO Items : Vorpal sword = Diadmon sword (Material)
Vanilla item : Diamond sword = Diadmon sword (material)

But good will be in gamble otpion only vanilla items. So maybe some 
configuration for false hook in MMO items?

**Additional context**
Thenk you so much for answer.

**Comment by snowgears** [comment]
You can put any items you want to get from gamble shops in the chest itself. If the chest is empty, it will pick a random recipe from the server instead.
