### ISSUE TITLE
 ClearLag - delete items

### ISSUE THREAD

**Issue by kristian198** [snowgears/shopbugs#213]
**I have a problem with items above the store (chest), if I have an item there that moves as if it was thrown away, then ClearLag will delete it for me. Is there any way to prevent this?**

**Version:**
 - Spigot version: git-Paper-629 (MC: 1.16.5)
 - Shop version: 1.8.2.4

**Comment by snowgears** [comment]
ClearLag support was dropped when it stopped publishing its API endpoint for other developers to use. You are better off using Paper or another means to deal with lag. ClearLag actually does not do much to reduce lag that can't be done by other better means.
