### ISSUE TITLE
Shop Plot Setting?

### ISSUE THREAD

**Issue by Dracathio** [snowgears/shopbugs#222]
Welp this is more of an enhance to current towny support.

If possible to have a setting that checks for shop plot and if they can build in the shop plot.

https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/utils/ShopPlotUtil.java  This seems to be the part for Shop Plugins to work best or for Shop Plots

**Comment by snowgears** [comment]
Added in 1.8.2.6 (in progress)
