### ISSUE TITLE
Armor stand wont go away

### ISSUE THREAD

**Issue by MrFalcon14** [snowgears/shopbugs#223]
Hi!

We love the plugin, but we have a few bugs to report after some tryouts.
1. Armor stands doesnt disappear/delete/get removed when we use the non showing shop display (displayCycle:
   - NONE)? Armor stands happen to take a lot of ticks and this causes a lot of chunck lag when creating massive shops.
2. The display texts cant be removed completely? When we delete the text in the config the black background for display text still appear. We also choose to set "displayNameTags: OFF" in the config, but black background for the text, still appears.. Its kind of annoying ;)

Server Version: Paper 1.16.5
Plugin Version: 1.8.2.5

Kind regards and hope you can help/fix! :)

**Comment by snowgears** [comment]
The variable in 1.8.2.5 changed from 'OFF' to 'NONE'. 

Please try setting displayNameTags: 'NONE', and then restart the server completely. Let me know if this does not fix the problem.
