### ISSUE TITLE
Add search feature to shop GUI

### ISSUE THREAD

**Issue by AbdulGhafoor01** [snowgears/shopbugs#226]
**Is your feature request related to a problem? Please describe.**
Yes: My Shopping Center is too big. It took 1 hour to find the specific item in the shopping center because of too many shops.

**Describe the solution you'd like**
Kindly add a feature that we can do /shopfind <itemname>

**Describe alternatives you've considered**
I think I already describe the solution and that is the only one solution

**Additional context**
None

**Comment by AbdulGhafoor01** [comment]
I also want to know that:
              Dose ShopConverter converts quick shop items too? with Premium Shops?

**Comment by snowgears** [comment]
You can quickly find shops selling a specific item with the shop GUI. This is the primary purpose and is getting a heavy rewrite to add better features like search. Feel free to use it in the meantime though it is in beta at the moment and quite memory intensive (which will be fixed).

Also, no ShopConverter currently is only for ChestShop. If you want other plugins supported too, please submit a separate feature request.

**Comment by AbdulGhafoor01** [comment]
Ok..

**Comment by snowgears** [comment]
This has been added in 1.8.2.8 (in progress)
