### ISSUE TITLE
Plugin hangs up when being enabled

### ISSUE THREAD

**Issue by Shnatta** [snowgears/shopbugs#228]
**Describe the bug**
The server stops responding when it's getting enabled thus creating an error. The exact error is shown twice 5 seconds later in the logs. 
- https://pastebin.com/jHHMAhGU
- https://pastebin.com/dZEwFQXH

**To Reproduce**
Not sure how.

**Expected behavior**
The server should enable properly and not throw errors. 

**Version:**
 - Spigot version: git-Airplane-8703980 (MC: 1.16.5) 
 - Shop version: 1.8.2.6

**Comment by Ste3et** [comment]
I think it is still present in shop version v 1.8.2.7

My complete latest.log looks like that: https://paste.gg/p/anonymous/548b5d5e8f3b4ae1bbb708ef4189d93f
The Server hangs and crash after the first join., but only with  the shop plugin  and with my saved shop files.

If i delte any kind of saved data from the shop plugin everthing works fine.
Regrads Ste3et_C0st

**Comment by snowgears** [comment]
Fixed in 1.8.2.8 (in progress)
