### ISSUE TITLE
Item Floating x2

### ISSUE THREAD

**Issue by RMalfroid** [snowgears/shopbugs#229]
**Describe the bug**
 Not 100% sure if it's a bug or just an issue with paper 1.17, but all chest shops that have the item floating above them will either disappear or show two floating.

**To Reproduce**
It's kind of like a server wide issue we're having so im not quite sure how to go about reproducing this issues besides literally just logging on.

**Expected behavior**
Items floating above the shop chest to be singular or not disappear when the chunk is unloaded and then revisited.
**Screenshots**
![shopitemdupe](https://user-images.githubusercontent.com/48326495/123860447-eaa0ee80-d8f3-11eb-97c5-5f7f798b341d.jpg)
![2021-06-29_16 14 23](https://user-images.githubusercontent.com/48326495/123861409-212b3900-d8f5-11eb-9f19-d5ccdf4c31fb.png)

**Version:**
 - Spigot version: This server is running Paper version git-Paper-53 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ad5526)
You are 11 version(s) behind
Previous version: git-Tuinity-"44e8e5d" (MC: 1.16.5)
 - Shop version: 1.8.2.5 (On version 1.8.2.6 the gui would not show players shops and what they sell, but the duplication of items on top of chests was fixed.)

**Additional context**

**Comment by snowgears** [comment]
This has been fixed in 1.8.2.7 (in progress)
