### ISSUE TITLE
[BUG] java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'

### ISSUE THREAD

**Issue by rrunswickjr** [snowgears/shopbugs#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: Purpur 1.17.1
- Shop Version: 1.8.2.7
```

### Server startup log

https://paste.gg/p/anonymous/f2d49f91c1624b65a9022d1b4669dc96

### Shop config files

https://paste.gg/p/anonymous/88912eeabc464ec9a867500dcab90435

### Error log (if applicable)

https://paste.gg/p/anonymous/7e92bd9fde674f208fa3ed456d3ae97c

### Bug description

Error in the console, intermittently appears.  Uncertain of cause.

### Steps to reproduce

Start the server

### Expected behaviour

No errors in console

### Actual behaviour

Errors in console- shop appears to function.

**Comment by rrunswickjr** [comment]
It looks like items aren't appearing over the chests either, upon further review.

**Comment by snowgears** [comment]
This is because NMS has changed a method in 1.17.1

This is fixed in version 1.8.2.8 (in progress)

**Comment by rrunswickjr** [comment]
Thank you for the information, looking forward to the update.  Let me know if I can do anything further to assist.
