### ISSUE TITLE
Only send display entities to players close enough to see them

### ISSUE THREAD

**Issue by zedwick** [snowgears/shopbugs#238]
**Is your feature request related to a problem? Please describe.**
It seems Shop may be sending all shop entities to players no matter where they are on the server. On my server I had *at-least* 450 entities shown on my F3 screen no matter where I went around the server. Reconnecting did not clear them. Removing the plugin was the only way to lower the entity count on F3.

**Describe the solution you'd like**
The shop display entities should only be sent to clients when the player is within a certain range, and removed when they are out of that range. 32 blocks would be a reasonable default limit to help ease client performance in shop areas.

**Comment by zedwick** [comment]
Just an additional detail: After a server restart the shop display entities are not sent to any players until the shops have been loaded in once. After that, even if the shops are no longer loaded, players will be sent the display items. All players are sent the entities, including players who have not been near the shops.

**Comment by snowgears** [comment]
Thanks for submitting this. This is the next improvement I have planned!

**Comment by snowgears** [comment]
@zedwick I have a test file for this. Are you willing to test? If you can post in the discord I can get you the file. https://discord.gg/GpSwEWS

**Comment by snowgears** [comment]
Fixed in 1.8.3 (in progress)
