### ISSUE TITLE
[BUG] World Blacklist Option Not Working

### ISSUE THREAD

**Issue by Relaxing9** [snowgears/shopbugs#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Data loss

### Environment

```markdown
- Server Version: Paper 1.17.1 (Build 112)
- Shop Version: 1.8.2.9
```

### Server startup log

https://paste.gg/p/anonymous/09d133efc42e4c5caf3221ec5970857d

### Shop config files

Desired: https://paste.gg/p/anonymous/1ca39952663d48d385fb3fbc29a91b87
Actual: https://paste.gg/p/anonymous/4d569539df0445bfa82d3024b0a685fa

### Bug description

When modifying the World Blacklist option and reloading the plugin (or restarting the server) the values are not saved on reload nor restart.

### Steps to reproduce

1. Open config.yml
2. Paste in the "worldBlacklist" your desired blacklist.
3. Either stop the server and paste these values in, or reload the plugin with the server running
4. Observe (config resets to default values and ignores the blacklist)

My setup:
`# Add the names of worlds that you do not want shops to be able to be created in here #
worldBlacklist:
  SurvivalSpawn_nether: true
  SurvivalSpawn_the_end: true`

### Expected behaviour

Expected for the worldBlacklist options to be saved on the config and to function (right now I don't know if they blacklist at all haven't tried, but it isn't saving)

### Actual behaviour

config resets and doesn't save worldBlackList options.

**Comment by snowgears** [comment]
Fixed in latest version (in progress)
