### ISSUE TITLE
The shop items keep disappearing without apparent Reason

### ISSUE THREAD

**Issue by ghost** [snowgears/shopbugs#24]
From time to time - without any reason, the items disappear, but the shop is operable. (Spigot 1.8.9).

I have removed Wildstacker and Clearlagg - still no change. Tried to keep chunkls loaded with KeepChungs - no effect. There is no message in the log that could hint to the solution. 

There is no preceeding event that could cause that behavior. 

It renders my server "useless" please help quickly (yumble.net), you can join and see yourself

**Comment by snowgears** [comment]
Have you tried removing any other plugins that may be clearing items in the background? Shop does not remove items so it must be another plugin that is doing it
