### ISSUE TITLE
[BUG] Anyone can open double chest shops if shop sign is on the LEFT

### ISSUE THREAD

**Issue by CW-UK** [snowgears/shopbugs#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: Paper 1.17
- Shop Version: 1.8.2.9
```

### Server startup log

https://gist.github.com/CW-UK/78c1e1f7bbe8ed8c2833438e5df94efc

### Shop config files

https://gist.github.com/CW-UK/7658a82ab19d695f619ae2bd8fc097ee

### Error log (if applicable)

N/A

### Bug description

Players can open any shop that is a double chest if the sell sign is placed on the **LEFT** of the chest. Double chest shops with signs on the RIGHT are not affected, nor are barrels and single chests.

### Steps to reproduce

- Create a double chest;
- Place a sell sign on the LEFT side of the double chest;
- Get another player to open the chest.

- Place a sign on the RIGHT side of the double chest;
- Chest can no longer be opened.

### Expected behaviour

Players should not be able to open other people's shop chests no matter which side the shop sign is on.

### Actual behaviour

Players can open other people's shops that are double chests if the shop sign is on the left.

**Comment by snowgears** [comment]
Fixed in 1.8.3 (in progress)
