### ISSUE TITLE
Multiple Currency Types

### ISSUE THREAD

**Issue by kingsolomon97** [snowgears/shopbugs#244]
Since not all servers use one standard currency (my players nearly rebelled when I suggested adding a coin-style currency or single item currency, they really hate most economy plugins apparently), the ability to have multiple defined currency types would be stellar. One possible way it could work is that it could be defined in the config with a list, including settings and all, or it could be defined via command similar to the /shop setcurrency command (perhaps /shop setcurrency {name}?). Then the shops can have their currency set through typing it on the sign, using a command (something like /shop changecurrency {currencyname}), or by smacking it with the appropriate item (like setting the item which the shop is selling)?

Additionally, since some servers (like mine) use different specific currencies for specific things (for example, we have a voting reward item that can only be attained through voting and can be spent at certain shops I have set up), the ability to set permissions for certain currencies would be extremely useful for some (a few) of us.

For example, having Emeralds, Diamonds, Gold, Experience (permission only given to admin), Voting Item (again, admin only), and Vault Currency (for servers other than mine) set as possible Currencies in the config would allow players to set whichever they want per shop though typing on the sign, a command, smacking it, or even the GUI.

It may seem like a fairly small thing, but your shop plugin so far is the best we have tried and is the closest to what we need, and is also one of the most intuitive and pretty shop plugins we have used, so it would be amazing if it could be flexible in this way.

**Comment by snowgears** [comment]
Isn't this basically a barter shop though? Couldn't you set a default item currency and players who want to accept another item currency can make a barter shop?

**Comment by kingsolomon97** [comment]
In my mind its a more permanent and slightly more convenient solution to it, though it occurs to me that uou are right that it would appear no different to the player if there were a way to make it so that only the recieved bartering item were displayed above the chest. I honestly find barter chests a bit confusing to set up, but if they could be more customized to just display one of the items that would essentially solve

**Comment by kingsolomon97** [comment]
Stupid buttons erasing all my text. In short, yes, it would look no different to the normal player, but it would (in my somewhat outside opinion) be a more unified/convenient solution. It would be nice to tell my players how to set up "sell" shops instead of "sell shops, unless you dont want diamonds, then barter shops". I also find barter shops to be somewhat confusing, but that might just be me.

That being said, if there were a way to make it so that barter shops only showed one item of the two in question, that would give a very similar outcome. If that is easier, then that totally makes sense too.

**Comment by snowgears** [comment]
Coming back to this. For now I am adding a wontfix label.

My reasoning is this overcomplicates things and barter shops already work for this use case. If there are special items in the server you want to be worth a certain amount of money, you can also have a shop hub where admin shops buy these special items from players for a specified amount of money. Then players can trade their special items for money, and then use that money at any shop. May reopen in the future but prioritizing other things for now as there are workarounds that make sense to me here.
