### ISSUE TITLE
update [stock color] on hopper feed

### ISSUE THREAD

**Issue by PotatoIQ** [snowgears/shopbugs#247]
**Is your feature request related to a problem? Please describe.**
When the shop is automatically restocked through dispenser, dropper or hopper the [stock color] doesn't update on the sign.

**Describe the solution you'd like**
Check for hopper, dropper, dispenser events and if they're feeding into the chest shop if the [stock color] is red, and change it to green if the shop is stocked through the hopper, dropper, dispenser.

**Describe alternatives you've considered**
player must remove the item manually by hand from the chest then readd it to update the color on the sign.

**Additional context**
N/A

**Comment by snowgears** [comment]
Currently marking this as 'wont fix' as InventoryMoveEvent is quite server intensive. This can be added easily via API though.
