### ISSUE TITLE
ItemFrames generated in incorrect facing positions 

### ISSUE THREAD

**Issue by GeRmAnAnToNiO124** [snowgears/shopbugs#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: 1.16.5
- Shop Version: 1.8.2.7
```

### Server startup log

https://haste.nealand.club/sijivehoki.makefile

### Shop config files

config default

### Bug description

As I mentioned in discord, the item frames are not presented correctly generating aesthetic but important problems.

### Steps to reproduce

1Create a store
2shift+click

### Expected behaviour

That the frame is in the correct position

### Actual behaviour

It generates a frame that instead of being correctly positioned is in an incorrect position.

**Comment by GeRmAnAnToNiO124** [comment]
.

**Comment by snowgears** [comment]
I have been unable to recreate this. I have done extensive testing on 1.16.5 and ItemFrames always come in correctly. Please open this again after trying on the latest version of 1.16.5 Spigot and a clean server.
