### ISSUE TITLE
Ability to sell contents of entire chest - mutliple different items

### ISSUE THREAD

**Issue by Virologicbody** [snowgears/shopbugs#252]
**Is your feature request related to a problem? Please describe.**
Ability to sell the entire contents of a chest where the contents could be several different items.

**Describe the solution you'd like**
When creating the sign for the chest, instead of entering a numerical value for the amount being sold, perhaps use the word 'all' or something similar.

**Describe alternatives you've considered**
Put all items in a 'non-shop' chest and hope players are honest enough to leave payment when they take the chest contents.

**Additional context**
E.g. this gives players the ability to sell things like kits of armor or a beacon including all of the blocks to make the beacon base.

![2021-08-28_22 30 13](https://user-images.githubusercontent.com/45987191/131231646-4667b89f-9515-4dcf-94a3-16af401fa7d7.png)

**Comment by snowgears** [comment]
This relies on honesty and will not be implemented.

A solution I would suggest is selling a special item that when used, will give the player who used it a full kit of armor, or whatever other set of item you configure. (or sell a shulker box containing these items, etc)
