### ISSUE TITLE
[BUG] &m doesn't work in chat config (strikethrough)

### ISSUE THREAD

**Issue by Plumzie** [snowgears/shopbugs#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: 1.16.5
- Shop Version: 1.8.2.5
```

### Server startup log

not relevant

### Shop config files

https://paste.gg/p/anonymous/7640177f8ba74eec9b573e568788d872

### Bug description

&m doesnt work in chat config and it resets the color as well to white

### Steps to reproduce

Use &m in chat config

### Expected behaviour

it would keep the color + make it strikethrough and not turn white

### Actual behaviour

it turns white when &m is used and doesn't do strikethrough

**Comment by Plumzie** [comment]
on further inspection &l seems to not work as well (and im guessing the other special codes)

**Comment by snowgears** [comment]
Have you tried changing the order?

i.e. "&m&c" vs "&c&m"

**Comment by snowgears** [comment]
Closing for now until question is answered.
