### ISSUE TITLE
[BUG] "deletePlayerShopsAfterXHoursOffline" does not work.

### ISSUE THREAD

**Issue by NotEvenAUnicorn** [snowgears/shopbugs#260]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: This server is running Purpur version git-Purpur-1385 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 529daae on ver/1.17.1)

- Shop Version: 1.8.3
```

### Server startup log

https://paste.gg/p/anonymous/7b23007ed45d48afa65d5e3d04aa9723

### Shop config files

https://paste.gg/p/anonymous/af280f3990794edda24fa97dd19c9d5b

### Bug description

"deletePlayerShopsAfterXHoursOffline" does not work, shops remain active after players are gone for 720+ hours

### Steps to reproduce

Have player create shop.
Player leaves for x amount of hours until shop expires as set in config.yml
Shop remains active.

### Expected behaviour

The shops should be deleted/unactive.

### Actual behaviour

The shops remain active.

**Comment by snowgears** [comment]
Fixed in 1.8.3.1 (in progress)
