### ISSUE TITLE
Add Essentials shop support to ShopConverter

### ISSUE THREAD

**Issue by NotEvenAUnicorn** [snowgears/shopbugs#265]
**Is your feature request related to a problem? Please describe.**
Not a problem with your plugin, but some of us are still, unfortunately, plagued by 1.12 shop features from Essentials.

**Describe the solution you'd like**
A way to convert these buy/sell signs to Shop.

**Describe alternatives you've considered**
I have considered changing all of the shops manually, but it's a pre-built skyblock world and there are easily over 100 shop signs and that just sounds super crappy to do. But if the conversion addition to Shop isn't possible or is a pita, I'll live and fix it manually. :)

**Additional context**
N/A

**Comment by snowgears** [comment]
Added in ShopConverter 1.1.3 (https://www.spigotmc.org/resources/shopconverter.26420/update?update=434292)
