### ISSUE TITLE
Shop markers on web map (Dynmap/Pl3xmap/Bluemap)

### ISSUE THREAD

**Issue by Orenji64** [snowgears/shopbugs#269]
## Proposal

I think a good option would be to have shops appear on web maps such as **Dynmap**, **Pl3xmap** or **Bluemap**. I've seen many other plugins do this well such as Chunky Border or Plot2Dynmap. I think this feature would be great for survival servers where players want to make there shops known by others. If not individual shops then I think a group of shops in an area could merge to one marker showing data for all of them.

### Marker Info
- Shop owner
- Shop type
- Item being sold/bought
- Price for item in chosen currency
- Shop stock
- Shop coordinates
### Marker Appearance
Markers would appear on a `Shops` layer. The icon could be a chest or diamond or, if possible, the item being sold.

Thanks for considering my idea!

**Comment by snowgears** [comment]
Added in 1.8.3.4 (this is untested so please message me in the discord to test before release)
