### ISSUE TITLE
[Feature] Features that could be useful 

### ISSUE THREAD

**Issue by arturek1666** [snowgears/shopbugs#27]
Hi I have a question so I wanted to make an adminshop but I still want the shop to have limits so player can only buy for example 1 block of diamond if there is diamond in that chest, but I don't want to use my user name our my admins user name but like a fake admin user name like: Admin is this possible?

I just want the adminshop to be more real just like in real life with means if there is no items in stock you can't buy it, but still want it to be adminshop as I don't want my admins our me to get money doing that..

Also would love to see a feature that if in shop you setup 1 item per cost if player clicks on a sign he will have option to buy or sell 64 items our 32 items. basically it will calculate from 1 item price to 64 automatically. Our even have option to buy up to 9 stacks straight away, that would be more easy than spamming the sign all times to get to specific amount xD.

Also just notice that there is /shop command and you can look at shops from gui with is nice but what about adding so you can buy items straight from that gui :).

What I say it's just an ideas of mine to make it easy for players :)

**Comment by snowgears** [comment]
Why not just create an admin player for your server and just use that one to create the shops?

**Comment by snowgears** [comment]
> Also would love to see a feature that if in shop you setup 1 item per cost if player clicks on a sign he will have option to buy or sell 64 items our 32 items. basically it will calculate from 1 item price to 64 automatically. Our even have option to buy up to 9 stacks straight away, that would be more easy than spamming the sign all times to get to specific amount xD.

This is a planned feature but has no ETA at the moment

Also just notice that there is /shop command and you can look at shops from gui with is nice but what about adding so you can buy items straight from that gui :).
This will not be implemented unfortunately. I want to keep the plugin as a chest shop plugin

**Comment by arturek1666** [comment]
I understand that you want to keep it as a chest shop plugin fair enough :). Thanks for so quick responds :).
Well yes you are correct I could create an admin account. Thanks again for quick responds ;)

**Comment by snowgears** [comment]
No problem at all!
