### ISSUE TITLE
[BUG] Hologram text slightly offset to left

### ISSUE THREAD

**Issue by TheMartyCZ** [snowgears/shopbugs#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: 1.18 paper #53
- Shop Version: 1.8.3.2
```

### Server startup log

not necessary

### Shop config files

https://paste.gg/p/anonymous/b9f64048f3654542b21a623c154f8591

### Bug description

I have a hologram outside.
![image](https://user-images.githubusercontent.com/45405349/144960495-9095dc02-637a-4cca-9776-5c869f484dd4.png)

### Steps to reproduce

1. insert my displayConfig
2. reload
3. and it is done

### Expected behaviour

none

### Actual behaviour

none

### Other information

I use CMI holograms.

**Comment by snowgears** [comment]
Appears to happen only on shops that face EAST or SOUTH

**Comment by snowgears** [comment]
Fixed in 1.8.3.3 (in progress)
