### ISSUE TITLE
1.8.3.3 - Players can steal items with minecart hoppper

### ISSUE THREAD

**Issue by InsideIntel** [snowgears/shopbugs#279]
![image](https://user-images.githubusercontent.com/50695683/146622946-d0b727c6-80d5-4dc1-a57f-c5c81c5ec0d2.png)
Here is a image of coreprotect telling me that hoppers took items from a chest that has a shop

**Comment by snowgears** [comment]
Block below shops are protected for this reason. Issue involving block being moved using pistons fixed in #285
