### ISSUE TITLE
[BUG]  /shop does not autocomplete on 1.18.1

### ISSUE THREAD

**Issue by hamcoremusic** [snowgears/shopbugs#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: 1.18.1
- Shop Version: 1.8.3.3
```

### Server startup log

https://bin.bloom.host/avuxijerih

### Shop config files

https://paste.gg/p/anonymous/ccb1c2ab61e0429c8baa53e546a2fb04

### Bug description

/shop does not come up in the TAB autocomplete list!

### Steps to reproduce

1. Do /shop
2. See no TAB complete pop-up

### Expected behaviour

/shop should not show "Incompatible command"

### Actual behaviour

/shop stays red when typed and states its an invalid command. The command still works though

**Comment by snowgears** [comment]
Added in 1.8.3.4 (in progress).

(Also make sure that non-operators have permission to auto complete as I noticed when testing that only operators could see the auto complete)
