### ISSUE TITLE
[BUG] 'Banner Pattern' shop display are off-set.

### ISSUE THREAD

**Issue by vintrove** [snowgears/shopbugs#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: PaperMC 1.18.1 (latest)
- Shop Version: 1.8.3.3
```

### Server startup log

-

### Shop config files

-

### Bug description

When you cycle through the different shop displays, one of the display options is not on top of the shop, it is one tile to the left. This applies to any 'Banner Pattern'

![image](https://user-images.githubusercontent.com/37943945/147962076-83c1b085-ffe7-44b0-80a6-16fff6df2b27.png)

### Steps to reproduce

Create a shop.
Use any of the 'Banner Pattern' as the item to sell.
Cycle through the different display options by right clicking (or shift right clicking)
One of the displays will not be on top of the block.

### Expected behaviour

Expected display on top of individual shops, not on other tiles.

### Actual behaviour

Display is one tile to the left of your shop instead of directly above it.

**Comment by snowgears** [comment]
Fixed in 1.8.3.4 (in progress)
