### ISSUE TITLE
Add configurable click actions

### ISSUE THREAD

**Issue by SteeltonMC** [snowgears/shopbugs#289]
This suggestion is NOT tied to any bugs/issues.

I would love if there was an option to change the action for what currently SHIFT-RIGHT-CLICK does on a shop

In order to see shops details, which can be very beneficial, the customer currently has to SHIFT-RIGHT-CLICK the chest, which may be confusing and not noticeable easily. 

It would be awesome if we could add the option to configure the action. Such as Left-clicking on a shop sign, would bring up the shop info instead. that way, a user can see the shop info, and purchase the shop with just Left and Right-click. No more confusing shift, trying to aim at the chest in just the right spot.  :)

I am really bad at wording, please let me know if you want me to try and rephrase.

**Comment by snowgears** [comment]
Maybe a config section where you can match each click action to a shop action

i.e.

displayShopInfo:
    - RIGHT_CLICK_CHEST
    - LEFT_CLICK_SIGN
transactWithShop:
    - RIGHT_CLICK_SIGN

etc...

**Comment by SteeltonMC** [comment]
Oh that would be amazing!

**Comment by snowgears** [comment]
Added in 1.8.3.6 (in progress)
