### ISSUE TITLE
Add support for Bluemap

### ISSUE THREAD

**Issue by Virologicbody** [snowgears/shopbugs#291]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Hook in to Bluemap to show shop details on an online map as per feature request #269 (now closed)

**Describe alternatives you've considered**
No other alternatives available for this plugin.

**Additional context**
https://github.com/snowgears/shopbugs/issues/269

**Comment by snowgears** [comment]
Added in 1.8.3.8 (in progress)

![image](https://user-images.githubusercontent.com/4141199/194400062-2dbdbad4-a2c5-4097-b1fd-9ab0b3d1a801.png)
