### ISSUE TITLE
Sometimes a player will get muted think they are trying to type a value for shop creation process

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#292]
I have a bug in 1.18 where sometimes a player will get muted and this message will appear every time they speak. It's on version 1.8.3.4
![2022-01-09 13_42_46-shop - Discord](https://user-images.githubusercontent.com/4141199/148698039-5072c1fc-317a-48d4-9d5a-30fa04ab8e3e.png)

and like a sign will appear in front of them
relogging fixes it apparently but then it can just happen again and that's annoying.
also this is kind of weird

![2022-01-09 13_43_40-shop - Discord](https://user-images.githubusercontent.com/4141199/148698065-6dd4b135-4ca1-43e5-a3d2-63178b07bba6.png)

**Comment by Fregnesisse** [comment]
I have same problem, so I can't use shops on my server right now, do you know when it will be fixed

**Comment by snowgears** [comment]
For a temporary fix you can turn off the ability to build shops via chat. (in config.yml)
`creationMethod:
   placeSign: true
   hitChest: false`

**Comment by snowgears** [comment]
Fixed in 1.8.3.6 (in progress)
