### ISSUE TITLE
A glass item appears if you try to click the sign with the barter item

### ISSUE THREAD

**Issue by Darkmager** [snowgears/shopbugs#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: paper 1.18 latest
- Shop Version: latest
```

### Server startup log

https://paste.gg/p/anonymous/03bea3f2b900458f914b208ccd8b6544

### Shop config files

https://paste.gg/p/anonymous/d8bbbbbb280b4b559710500e35f629ef

### Bug description

when u click the sign with barter item a glass will appear on the chest and u have to restart the server

### Steps to reproduce

when u click the sign with barter item a glass will appear on the chest and u have to restart the server

### Expected behaviour

changing sign style

### Actual behaviour

when u click the sign with barter item a glass will appear on the chest and u have to restart the server

### Other information

https://imgur.com/a/NqJUzJr
https://easyupload.io/k7cwzj video

**Comment by snowgears** [comment]
Fixed in 1.8.3.6 (in progress)
