### ISSUE TITLE
add support for AdvancedRegionMarket

### ISSUE THREAD

**Issue by BoolyStudy** [snowgears/shopbugs#296]
support AdvancedRegionMarket please.

**Comment by doitliketyler** [comment]
Any updates on this? Would very much like support for AdvanedRegionMarket added.

**Comment by snowgears** [comment]
I am planning a large "integrations" update soon!

**Comment by doitliketyler** [comment]
That's great. I'll be looking forward to it. Thank you!

**Comment by snowgears** [comment]
Added in 1.8.4 (in progress)
