### ISSUE TITLE
Log shop purchases and actions

### ISSUE THREAD

**Issue by SeruhioX** [snowgears/shopbugs#30]
I would like to suggest that you register and keep in a file who buys and sells items, how much money they buy or sell, and details of the item, such as the name.
An example:

"Client: Player1, Owner: Player2, Operation: sell, Items:" Item name "(What item is) lore and enchantments, Price: $ xxx"

**Comment by snowgears** [comment]
I used to have more robust logging but it was removed at a certain point. Keeping this open to add later.

**Comment by snowgears** [comment]
Added support for SQL logging for MariaDB and MySQL in 1.8.3.6 (in progress)
