### ISSUE TITLE
[BUG] Dynmap getMarkerAPI

### ISSUE THREAD

**Issue by ToonamiSenpai** [snowgears/shopbugs#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue, Error in console, Other unexpected behaviour

### Environment

```markdown
- Server Version: 1.18.1
- Shop Version: 1.8.3.4
```

### Server startup log

https://paste.gg/p/anonymous/9ec8fcf898dc40c98b487b939b13865a

### Shop config files

https://paste.gg/p/anonymous/bad194f8a53345069ed44d01b8ed6d52

### Bug description

Shop wont start due to dynmap error

### Steps to reproduce

Start server
Have dynmap v3.3-beta-4
and latest Shop
and error

### Expected behaviour

Shop should enable and run

### Actual behaviour

Shop disables it's self

**Comment by snowgears** [comment]
Should have been fixed in 1.8.3.5

Please reopen if it comes up again
