### ISSUE TITLE
Let 1.12.2 support more features

### ISSUE THREAD

**Issue by StarDream521** [snowgears/shopbugs#305]
Can 1.12.2 be updated with newer features? We need it, the plugin is now a better plugin than quickshop. Ask the developers to make 1.12.2 support the new features!
![1 12 2](https://user-images.githubusercontent.com/40490183/158606251-12165bdd-8966-4c40-a8ef-168f63abf8a5.png)

**Comment by snowgears** [comment]
The next update will have a 1.8-1.13 release!
