### ISSUE TITLE
[BUG] Search feature players loose flight

### ISSUE THREAD

**Issue by RedShaunia** [snowgears/shopbugs#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: Paper 1.18.1 #177
- Shop Version: 1.8.3.4
```

### Server startup log

-

### Shop config files

https://pastebin.com/viUzPvD6

### Bug description

When players are in flight and use the shop search feature they loose /fly

### Steps to reproduce

-

### Expected behaviour

-

### Actual behaviour

-

**Comment by snowgears** [comment]
Fixed in 1.8.3.6 (in progress)
