### ISSUE TITLE
Relocate HikariCP

### ISSUE THREAD

**Issue by Ste3et** [snowgears/shopbugs#315]
Is your feature request related to a problem? Please describe.
[HikariConfig ](https://paste.gg/p/anonymous/4f298f9acb564b1eb67e28ea5301ccdc)

Describe the solution you'd like
Hello SnowGears can you pleace relocate the HikariCP to another package?
Another plugins who use HikariCP and didn't relocate the packe make trouble because using different versions of HikariCP 

Describe alternatives you've considered
n/a

Additional context
The issue is throwed because the plugins use not 100% exact the same HikariCP

**Comment by snowgears** [comment]
Fixed in 1.8.3.7 (in progress)
