### ISSUE TITLE
[BUG] shop.buildlimit.# issue

### ISSUE THREAD

**Issue by skrevt** [snowgears/shopbugs#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: 1.18.2
- Shop Version: 1.8.3.6
```

### Server startup log

https://paste.gg/p/anonymous/b2436a09049b401fac739cd85b88cf08

### Shop config files

https://paste.gg/p/anonymous/b2436a09049b401fac739cd85b88cf08

### Bug description

My Defaut players have shop.buildlimit.0 so they can't create a store, but when I add shop.buildlimit.5 to them they still can't create one, message comes, ;;You have reached the buildlimit of 0;;

If I remove the permission shop.buildlimit.0 this player only has the shop.buildlimit.5 this message still comes and no store can be created.

But if a player has only store.buildlimit.5 the message comes up that the buildlimit of 0 is reached.

I sell ingame the rights that players can create stores, that's why they have store.buildlimit.0 at the beginning.

Yes there have the permissions to create stores.

### Steps to reproduce

Create a Simple Shop via Signs

### Expected behaviour

That the store creations can be limited

### Actual behaviour

Unlimited Shop creations with buildlimit permission

**Comment by snowgears** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/4141199/167045759-762caa8a-b934-4bd8-9b32-bca0992f9ad0.png)
![Screenshot_2](https://user-images.githubusercontent.com/4141199/167045760-8f0f0787-80ca-4927-a9d0-d333ad5efc8e.png)

**Comment by snowgears** [comment]
“ I found it, Luckperms runs with me over bungee and on all subservers, if I give the player the permission only on the subserver everything goes without problems, but if I give him the right on the whole bungee nothing goes.

So it all works I found it out”
