### ISSUE TITLE
Add additional settings for sign price text

### ISSUE THREAD

**Issue by FelixGrasul** [snowgears/shopbugs#318]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a wish of mine

**Describe the solution you'd like**
I would love to see 10,000$/100,000$ instead of 100k$/10k$ and i couln`t find where to fix it

**Describe alternatives you've considered**
To let the plugin users to modify either to see 100k$ or 100.000$, based on their preferences 

**Additional context**
I don`t think there is a need for one

**Comment by snowgears** [comment]
Added in 1.8.4 (in progress)
