### ISSUE TITLE
[BUG] creation limit 

### ISSUE THREAD

**Issue by FelixGrasul** [snowgears/shopbugs#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Performance issue or memory leak

### Environment

```markdown
- Server Version: Paper 1.18.1
- Shop Version: 1.8.3.6
```

### Server startup log

https://paste.gg/p/anonymous/dae7fc0759cc464d8a901f1ea67e6ebf

### Shop config files

https://paste.gg/p/anonymous/343ac8e8aa1e404892f0497348a7047a

### Bug description

When I reload the plugin, the shop limits just stops working. The shop limits I mean the maximum shops a person can do. The only way to fix it is by restarting the server.

### Steps to reproduce

1. Reload
2.  See how the limit stops working

### Expected behaviour

The limit to don`t stop working

### Actual behaviour

When I reload the plugin, the shop limits just stops working. The shop limits I mean the maximum shops a person can do. The only way to fix it is by restarting the server.

**Comment by snowgears** [comment]
Shop buildlimit permissions are assigned at player login. If permissions change while the player is online, this can be fixed by logging out and logging back in. If the request is for a command to run to refresh permissions, please comment that here and I will reopen the ticket
