### ISSUE TITLE
Click again to confirm transaction / Click to show item being sold

### ISSUE THREAD

**Issue by hamcoremusic** [snowgears/shopbugs#32]
**Is your feature request related to a problem? Please describe.**
I feel that if you have a large shop with lets say, different potions, it's kind of a pain to label each one with the name. Also, sometimes you may mis-click and get an item you do not want.

**Describe the solution you'd like**
A cool way to overcome this problem would be to do a "click again to confirm transaction" feature.

I think this could also be an opportunity to tell the player that is buying the item what it is! For example, I have a Strength II potion shop; when I click the sign, it would ask "Right click again to to buy 1 Strength II potion for 1 Emerald."

**Describe alternatives you've considered**
Another way to show the item is if when you walked up to the shop and you were ~1 block away, a hologram would tell you the item being sold.

**Comment by snowgears** [comment]
Players can already click the chest of the shop to see the exact item being sold (when they hover over the item that tag that is sent to them in the chat window). This displays all attributes and then the player can decide if they want to buy or not from there.

**Comment by snowgears** [comment]
It prints an item in chat in square brackets (for example: [Stone]) and when hovering over this item in the chat with your cursor it will pop up a window showing the exact attributes of the item.
