### ISSUE TITLE
Add customization for MySQL connection properties

### ISSUE THREAD

**Issue by DopiGFX** [snowgears/shopbugs#320]
**Is your feature request related to a problem? Please describe.**
I wanted to use the new transaction logging feature with MySQL, but I got an error, because the flag "allowPublicKeyRetrieval=true" was not set as standard property in the plugin.
For me there are reasons why this setting is enabled on my Database-Server, so I'd love to be able to set custom connection-flags for the MySQL connection, such as: useSSL, characterEncoding, useUnicode, allowPublicKeyRetrieval and so on

**Describe the solution you'd like**
The best would be a section in the config where the users can set their own connection properties. (See below)

**Describe alternatives you've considered**
The alternative would be to change the settings of the database which is not an option for me.

**Additional context**
![image](https://user-images.githubusercontent.com/67605541/167297539-6f9ec444-d9c0-48bf-a430-d8e332f6b58f.png)

**Comment by snowgears** [comment]
Added in 1.8.3.7 (in progress)
