### ISSUE TITLE
[BUG] transactWithShopFullStack action buys ALL stock

### ISSUE THREAD

**Issue by zedwick** [snowgears/shopbugs#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)
- Shop Version: 1.8.3.6
```

### Server startup log

NA

### Shop config files

NA

### Bug description

As far as I can tell the intention of the transactWithShopFullStack is to buy up to one stack of an item from the shop, however it seems it will instead buy up all the available stock.

For example I traded 52 of my Iron Ingots for 520 Nether Warts. (a stack of nether wart is <=64)

### Steps to reproduce

1. Create a trade shop
2. Fill shop with multiple stacks of items to be traded
3. Right click sign to trade items

### Expected behaviour

Players should receive up to a full stack of the item

### Actual behaviour

Players receive multiple stacks of items, filling up all available space in their inventory.

**Comment by snowgears** [comment]
Fixed in 1.8.3.7 (in progress)
