### ISSUE TITLE
Allow action mappings to be disabled entirely

### ISSUE THREAD

**Issue by zedwick** [snowgears/shopbugs#324]
**Is your feature request related to a problem? Please describe.**
I would like to disable trading full stacks of items, as in my opinion it could lead to players unintentionally purchasing more than they intended.

**Describe the solution you'd like**
In the config there is the following line under `actionMappings`:

```
transactWithShopFullStack: 'SHIFT_RIGHT_CLICK_SIGN'
```

I would like to be able to disable this entirely, rather than setting it to an available player control. I tried changing it to `NONE` which would conform to other config options.

**Describe alternatives you've considered**
A separate toggle within the config to enable/disable the feature would be fine, also. However I had imagined other people may want to disable other action mappings, so that would be a more versatile solution.

**Additional context**

**Comment by snowgears** [comment]
Added in 1.8.3.7 (in progress)
