### ISSUE TITLE
[BUG] Moving to paper reset shop signs

### ISSUE THREAD

**Issue by Yukylyu** [snowgears/shopbugs#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: paper(66) 1.18-R0.1
- Shop Version: Shop-1.8.3.3 or Shop v1.8.3.6

 (screen: https://zupimages.net/up/22/24/ngvi.png ) i think is a paper problem :/ I changed from spigot to paper spigot, The problem appeared several days later.
```

### Server startup log

https://pastebin.com/iANKZpW1

### Shop config files

https://pastebin.com/tX9436dy (config) / https://pastebin.com/xDJEekjk (signconfig)

### Bug description

Hi, I have a problem that appeared all of a sudden and that I don't understand, the display of almost all of my shop panels have reset (screen: https://zupimages.net/up/22/24/ngvi.png )

### Steps to reproduce

create a shop or old shop

### Expected behaviour

I want the appearance of the configuration in signConfig.yml

### Actual behaviour

the shop work but signConfig.yml does not work anymore

### Other information

if i test a backup of my server i have this error https://pastebin.com/LhVTLd5X

**Comment by snowgears** [comment]
Do the signs still work as shops or did the shop get deleted entirely?

**Comment by Yukylyu** [comment]
yes the signs still work as shops, it's the visual of the sign that breaks, this is strange...

**Comment by snowgears** [comment]
It looks like this blank sign issue is a known mojang bug. Please see a fix here:
https://github.com/UltraVanilla/cleanupstupidmojangshit
