### ISSUE TITLE
[BUG] new 1.19 enchantments don't show correct names

### ISSUE THREAD

**Issue by LEOcab** [snowgears/shopbugs#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: Paper 1.19
- Shop Version: 1.8.3.7
```

### Server startup log

n/a

### Shop config files

https://paste.gg/p/anonymous/dd909fc9f9f04f0fb2e8b9aa7a36f63f

### Bug description

If a player tries to sell Swift Sneak books, it'll show up as an "Unknown" enchantment and only allow one sale before claiming to be out of stock

### Steps to reproduce

1. Create a shop selling a Swift Sneak book
2. Attempt to buy more than one

### Expected behaviour

The shop should let players empty the stock

### Actual behaviour

The shop claims it is out of stock after the first sale, even if there is plenty of stock in the chest

### Other information

thanks snow :D

**Comment by snowgears** [comment]
Fixed in 1.8.3.8 (in progress)
