### ISSUE TITLE
[BUG] WorldGuard hook break shop destroy protection

### ISSUE THREAD

**Issue by assada** [snowgears/shopbugs#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue, Other unexpected behaviour

### Environment

```markdown
- Server Version: Paper 1.18.2
- Shop Version: 1.8.3.7
```

### Server startup log

https://gist.github.com/assada/215905e4fbaed8219e2af5f81aa9fd15

### Shop config files

https://gist.github.com/assada/11ec3f67f952b7c27477d8bff6f6fc53

### Bug description

With enabled  WorldGuard hook `hookWorldGuard: true` any player can breaks any chest shop. 

### Steps to reproduce

1. Set `hookWorldGuard: true`
2. Create shop by Player A.
3. Break this shop by Player B

### Expected behaviour

Player B can`t break shop created by other player

### Actual behaviour

Player B break shop created by other player without any messages\errors

**Comment by snowgears** [comment]
Revisiting this to make sure the loop is closed!

The current functionality is that the region owner can destroy any other shop in their region if they own it. Is this not what is expected?

**Comment by snowgears** [comment]
Closing as I have not heard back in 2 months
