### ISSUE TITLE
BentoBox integration request - shops not removed when world chunks are reset

### ISSUE THREAD

**Issue by J4im3x0** [snowgears/shopbugs#333]
- It's request related and also a problem

- Can be solved creating an addon for BentoBox plugin

- I want to my players be able to have their shop in their islands, but the problem is when they delete/reset the island;  the shops will not be deleted because there is no hook into BentoBox (BSkyblock) plugin

Check the documentation of BentoBox https://docs.bentobox.world/en/latest/Tutorials/api/Create-an-addon/

*** Already tried doing shop reload or loading again the chunk to make the plugin delete the disappeared shop, but does not works. Also is not a good solution because the plugin needs to check more than can be using an addon (unique called on island delete)

**Comment by snowgears** [comment]
Added in 1.8.4 (in progress)
