### ISSUE TITLE
[Enhancement] Add sort options for shops in GUI

### ISSUE THREAD

**Issue by Firepup6500** [snowgears/shopbugs#335]
**Is your feature request related to a problem? Please describe.**
It's annoying to look through multiple pages of shops with seemingly no rhyme or reason to their order.

**Describe the solution you'd like**
Add an option to sort the shops by date added, total number of shops, alphabetical, etc.

**Describe alternatives you've considered**
Make alphabetizing the list default

**Additional context**

**Comment by snowgears** [comment]
Added in 1.8.3.9 (in progress)
