### ISSUE TITLE
[BUG] Shop Hologram 

### ISSUE THREAD

**Issue by byNixo** [snowgears/shopbugs#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: Paper 1.18.2
- Shop Version: 1.8.3.7
```

### Server startup log

https://paste.gg/p/anonymous/45b83a0b56834552aba6a9dcd19b1a41

### Shop config files

https://paste.gg/p/anonymous/a12f4996ed4a48cda90191f014c5e92c

### Bug description

I don't know exactly how that happened. The shop went empty and I spammed it with sneak, I don't know

### Steps to reproduce

1. create a shop
2. spamming at the sign if the shop is empty

### Expected behaviour

You cannot remove the hologram

### Actual behaviour

The hologram is permanent and the sell item is duplicated

### Other information

![grafik](https://user-images.githubusercontent.com/74796414/189342914-ec38eb00-4551-4b78-86d8-737c4e8b95d7.png)

**Comment by snowgears** [comment]
All holograms are client side. If you log out and log back in the hologram will be gone.
