### ISSUE TITLE
shift-punch chest creation method not working

### ISSUE THREAD

**Issue by mitchngwen** [snowgears/shopbugs#339]
There are no error logs

When you shift punch a chest you can make a buy shop but it you just punch the chest it does nothing.

**What are the known conflicting plugins? I'll take a look there and then get back to you.**

**Comment by snowgears** [comment]
If a plugin is blocking the interact event, Shop will not be able to pick that event up. It sounds like this is a plugin conflict

**Comment by snowgears** [comment]
Closing this issue until question is answered
