### ISSUE TITLE
Change the hologram behavior so it doesn't disappear when you look at it

### ISSUE THREAD

**Issue by aaron-rust** [snowgears/shopbugs#345]
**Is your feature request related to a problem? Please describe.**
When standing in front of a shop the hologram only shows when looking directly at the sign. Therefore when you look up from the sign to see the hologram it immediately disappears making it unreadable. 

**Describe the solution you'd like**
I want the hologram to stay when you look at it. Therefore the plugin should check if the player looks at the sign, barrel/chest or the two blocks above the shop. This way the hologram also stays if it looked directly at.

**Describe alternatives you've considered**
Right now you can set a delay in the config.yml "displayNameTagsLifespan" f.e. 5 seconds, but this doesn't solve the problem. When you have multiple shops next to each other and want to check one after another, the holograms will overlap, because they don't disappear quickly enough.

![2022-10-09 13-24-35 mkv](https://user-images.githubusercontent.com/16528263/194754202-1d49315d-6e9c-42bb-a2a5-348215c6e7de.gif)

**Comment by snowgears** [comment]
Added in 1.8.4 (in progress)
