### ISSUE TITLE
Allow Geyser Mobile player to make shop with eating animation items

### ISSUE THREAD

**Issue by Darkmager** [snowgears/shopbugs#350]
So currently the mobile players cannot make shop by potions or any eatable items , when you make the sign and try to click on with it the player just shows consume animation (happens only in mobile bedrock)

**Comment by snowgears** [comment]
This is not a shop bug, but seems to be a limitation of Geyser or bedrock mobile. I opened a ticket in Geyser here for you to track! https://github.com/GeyserMC/Geyser/issues/3393
