### ISSUE TITLE
[BUG] Buy Shops Show As Out of Stock

### ISSUE THREAD

**Issue by SiuanSong** [snowgears/shopbugs#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: Purpur 1.19.2 #1832
- Shop Version: 1.8.3.9
```

### Server startup log

https://gist.github.com/SiuanSong/a67e5a4367e035e0f4a7463e871298a2

### Shop config files

https://gist.github.com/SiuanSong/1aa76ef9cf309326cca31310bb1f5efb

### Bug description

Buy Shop Signs show as red (out of stock) and hitting the chest for information shows Stock: 0, despite there being adequate stock and the shop working properly.

![javaw_QCtOBIic4U](https://user-images.githubusercontent.com/28202890/200090466-d6d3a48d-5053-4fd5-88a8-101e37add383.png)

### Steps to reproduce

1.  Create a Buy Shop

### Expected behaviour

Stock amount should be read properly

### Actual behaviour

No stock inventory is read

**Comment by snowgears** [comment]
Fixed in 1.8.4 ( in progress)
