### ISSUE TITLE
CommandToItem Support

### ISSUE THREAD

**Issue by Wastinqs** [snowgears/shopbugs#352]
Please add a support for CommandToItem

These are items with minecraft:infinity:1 enchantments

https://www.spigotmc.org/resources/commandtoitem-1-8-1-19-custom-consumable-command-items.19937/

Thanks a lot!

**Comment by snowgears** [comment]
This is an issue with the way CommandToItems cancels all PlayerInteractEvents. I have proposed a fix here but it is up to the developer of that plugin to implement this. https://github.com/LMBishop/CommandToItem/issues/14

**Comment by snowgears** [comment]
Closing this issue, as its an issue with CommandToItem, not Shop. A fix has been requested.
