### ISSUE TITLE
A /shop togglenotify command 

### ISSUE THREAD

**Issue by byNixo** [snowgears/shopbugs#356]
**Is your feature request related to a problem? Please describe.**

Players get a lot of messages in chat, command is handy to disable them.

**Describe alternatives you've considered**

Currently there is none

**Additional context**

Players can disable notifications when a player buys/sells items using the /shop togglenotify command

**Comment by snowgears** [comment]
This command already exists.

**/shop notify [user/owner/stock]** - toggle your own player specific notifications for when you use a shop, when a player uses one of your own shops, or when one of your shops runs out of stock

It is also available to users via the GUI for toggling specific notifications from shop.
