### ISSUE TITLE
[BUG] AdvancedRegionMarket - player data doesn't update at region reset

### ISSUE THREAD

**Issue by Qinak** [snowgears/shopbugs#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: Paper 280
- Shop Version: 1.8.4
```

### Server startup log

https://gist.github.com/Qinak/1b1d250a266e1f30324e4ef225d56e98#file-gistfile1-txt

### Shop config files

Default files

### Bug description

A players shops inside a AdvancedRegionMarket region getting reset doesn't get removed from the data `.yml` file.

### Steps to reproduce

Adam rents a region and create shops. The region resets but their storage `.yml` doesn't update at this point.
Billy can now rent and create shops in the exact same spot, restart the server and now it's Adams shops.
If Adam creates a shop somewhere, now the data `.yml` gets updated and the old shops gets removed from the file.

### Expected behaviour

The shop-data to be reset or updated when the region is.

### Actual behaviour

Players shop that was removed by a region getting reset is updated only when he creates a new shop.

**Comment by snowgears** [comment]
Fixed in 1.8.4.1 (in progress)
