### ISSUE TITLE
Add shop manager

### ISSUE THREAD

**Issue by DaddyRobLIVE** [snowgears/shopbugs#367]
**Describe the solution you'd like**
Allows you to add a shop manager that can restock or manage the shop for you.

The previous trade shop plugin I'm using has this feature. I hope you guys, would consider this as well.

**Comment by OstlerDev** [comment]
This is definitely something we want to add, I am going to close this in favor of this more recent ticket (to keep track of it easier).

Duplicate of: https://github.com/snowgears/shopbugs/issues/435
