### ISSUE TITLE
Error when clicking to see player shops in Gui

### ISSUE THREAD

**Issue by arizrain1** [snowgears/shopbugs#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Spigot version: [e.g. Spigot 1.13.2, Paper-Spigot 1.12.1, etc]
 - Shop version [e.g. 1.7.3.2]

**Additional context**

**Comment by snowgears** [comment]
Please remove your guiConfig.yml file and allow a new one to generate. It appears there is still a STAINED_GLASS_PANE field in your config for an item (which no longer exists in the 1.13 API).

**Comment by arizrain1** [comment]
This is what is in the guiConfig.yml before and after re-generating one.  

      last_page:
         type: "RED_STAINED_GLASS_PANE"
         name: "Previous Page"
         lore:
            - "&7Go back."
      next_page:
         type: "RED_STAINED_GLASS_PANE"
         name: "Next Page"
         lore:
            - "&7Go forward." 

This is the error in Console when we click on player shops inside the /shop   gui
"Your Shops" works fine.

**Comment by snowgears** [comment]
Can you post the error that happens with your new config?

**Comment by arizrain1** [comment]
Error when we click 'playershops'          https://pastebin.com/3GDbx9Ds

My guiConfig:            https://pastebin.com/7d6xw3gi

**Comment by arizrain1** [comment]
Any progress on this?

**Comment by snowgears** [comment]
This fix will be included in the next update.

**Comment by arizrain1** [comment]
Thank you so much for all your hard work.  We absolutely love your plugin :)

**Comment by KlenerTeufel96** [comment]
When will the update come out? Wie need the fix asap :)

**Comment by gaRt3n** [comment]
@snowgears update please? Got the Same Pane Error even when i changed it. Or just give the Source and ill fix it by myself

**Comment by BillyGalbreath** [comment]
Fixed in next release
