### ISSUE TITLE
[BUG] Shops cannot be created on 1.19.3

### ISSUE THREAD

**Issue by RhythmicSys** [snowgears/shopbugs#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue, Error in console

### Environment

```markdown
- Server Version: `Purpur 1.19.3-1864`
- Shop Version: `Shop v1.8.4`
```

### Server startup log

https://mclo.gs/H1pCcUc

### Shop config files

https://mclo.gs/ZpRLQTR

### Bug description

Shops cannot be created on a 1.19.3 server
`/shop` works, and it catches when you've partially created a sign, but a full sign causes a NPE

### Steps to reproduce

be on 1.19.3
create a shop

### Expected behaviour

a shop would be created

### Actual behaviour

no shop is created, and there is errors in console

**Comment by snowgears** [comment]
Fixed in 1.8.4.1 (in progress)
