### ISSUE TITLE
[BUG] Hikari maxLifetime warning

### ISSUE THREAD

**Issue by untuned** [snowgears/shopbugs#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: git-Purpur-1862 (MC: 1.19.3)*
- Shop Version: 1.8.4.1
```

### Server startup log

N/A

### Shop config files

N/A

### Error log (if applicable)

https://paste.hep.gg/cohiv.less

### Bug description

Hikari posts this error in console. Nothing seems to be affected, just a bit annoying.

### Steps to reproduce

Set-up MySQL for transaction logging.
Leave server running with players joining and leaving over a period of time.

### Expected behaviour

The messages shouldn't be in console.

### Actual behaviour

The messages post to console.

**Comment by snowgears** [comment]
Fixed in 1.8.4.2 (in progress)
