### ISSUE TITLE
Shop seems to be "Rounding" to the nearest values. 

### ISSUE THREAD

**Issue by Palycraft** [snowgears/shopbugs#380]
Hey, I just noticed a weird issue:
https://gyazo.com/61d9a50d8f7c80c5f35d6c97752b7782

![2022-12-30_17 41 20](https://user-images.githubusercontent.com/22733892/210116161-b30d8de1-5e52-4700-b4f0-1ed40d14efa8.png)

So I gave myself 17 wheat, sold it at a 32 wheat for 1 gold ingot. And it let me sell the 17 wheat for 1 ingot. Not sure why

**Comment by snowgears** [comment]
Fixed in 1.8.4.2 (in progress)
