### ISSUE TITLE
Buy Shop showing an error in console on creation

### ISSUE THREAD

**Issue by GHCupex** [snowgears/shopbugs#381]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: 1.19.2
- Shop Version: 1.8.4.1
```

### Server startup log

https://paste.gg/p/anonymous/04b53b26df3c4be5ad2016e6be81dd23

### Shop config files

https://paste.gg/p/anonymous/95bd27b79d8c4dd1bdb715149bfa2425

### Error log (if applicable)

See the image below. Somehow that slipped

### Bug description

![Screenshot 2023-01-04 012343](https://user-images.githubusercontent.com/102182986/210521666-ecd97372-4ce3-404f-8d54-73180550f54f.png)

### Steps to reproduce

1. Create a buy shop
2. The error pops up

### Expected behaviour

There should be no Error and it should be like the sell shop only with buy

### Actual behaviour

Nothing. The Error pops up

**Comment by ZappySK** [comment]
I have the same problem, author will fix it in the new update :33

**Comment by snowgears** [comment]
Fixed in 1.8.4.2 (in progress)
