### ISSUE TITLE
[BUG] Suspicious stews cannot be recognized after restart.

### ISSUE THREAD

**Issue by Peashooter101** [snowgears/shopbugs#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: Purpur 1884 (MC: 1.19.3)
- Shop Version: 1.8.4.1
```

### Server startup log

https://paste.gg/p/anonymous/0b8e36202c3f4367b217ac330a3365f1

### Shop config files

https://paste.gg/p/anonymous/7f6d259b29d04b419c2f53f9e349961d

### Bug description

Setting up a shop using Suspicious Stews works but only initially.

The stock on the shop is set to 0 after server restart it seems (Attempted to replicate on chunk unload but I could not manage to get it to replicate). Pulling items out of and putting items into the shop does not add or remove stock to the number as well, the items are just not recognized as the sell items.

On shop creation, all stews are recognized correctly and can be sold to other players initially, works afaik.

### Steps to reproduce

1. Obtain a specific type of Suspicious Stew.
2. Create a sell shop.
3. Restart the Server.

### Expected behaviour

Suspicious Stews should still be capable of being sold to the player.

### Actual behaviour

The shop no longer recognizes the Suspicious Stews and no longer is able to sell them to the player, the shop is marked as out of stock until the sell sign is replaced.

### Other information

![image](https://user-images.githubusercontent.com/20095065/211686390-62249346-4b9b-4712-8aca-baed0cfb8b82.png)
![image](https://user-images.githubusercontent.com/20095065/211686475-152d46e0-3d78-4393-a67f-ab634d10a8ba.png)
![image](https://user-images.githubusercontent.com/20095065/211686680-ad3f8409-dabe-4f76-ba3a-838823592366.png)
![image](https://user-images.githubusercontent.com/20095065/211686692-819901c2-d8fe-4c4e-b80f-929c75cd61ac.png)

**Comment by snowgears** [comment]
Fixed in 1.8.4.2 (in progress)
