### ISSUE TITLE
[BUG] InventoryCloseEvent on Enderchest throws an error when location is null

### ISSUE THREAD

**Issue by RhythmicSys** [snowgears/shopbugs#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: Current: git-Purpur-1888 (MC: 1.19.3)
- Shop Version: 1.8.4.2
```

### Server startup log

https://mclo.gs/nmtHdyI

### Shop config files

https://mclo.gs/gRy1eUl

### Error log (if applicable)

https://pastebin.com/38E88hbH

### Bug description

If a player uses the command `/ec` to open their enderchest, it sends errors in console 

### Steps to reproduce

Have a plugin that opens an enderchest without a location
open enderchest
error in console

### Expected behaviour

There would be no error

### Actual behaviour

There is an error

### Other information

Enderchest has been removed as a usable shop item, as suggested in [this bug report](https://github.com/snowgears/shopbugs/issues/372#issuecomment-1399343123) which has not stopped the issue
Enderchest command comes from [this plugin](https://github.com/ADHDMC/SimplePlayerUtils) using [this method](https://github.com/ADHDMC/SimplePlayerUtils/blob/master/src/main/java/adhdmc/simpleplayerutils/commands/inventories/EnderchestCommand.java#L69)

**Comment by snowgears** [comment]
This was fixed in a patchfix uploaded to Spigot. Please download the latest version (still 1.8.4.2 on Spigot). I reuploaded and fixed this.

**Comment by SoundGamingYT** [comment]
Bug is still happening.
