### ISSUE TITLE
Admin shops on any block

### ISSUE THREAD

**Issue by Plumzie** [snowgears/shopbugs#39]
It seems like you are only able to make admin shops on chests or inventories and this annoys me as I want to have a wall of signs with prices and such but cannot put them on the wall. It would be nice to be able to specify what blocks an adminshop can be placed on or allow them to be placed on anything with the display disabled. The closest thing I could get to a wall of signs was on shulker boxes but they look strange.

**Comment by snowgears** [comment]
I understand why you would want this as a feature but I designed the plugin like this so that all shops would have a unified look and experience. This is currently not planned but if anyone else wants to vote on this or add additional comments I am open to listening.

**Comment by Segysmundo** [comment]
> but if anyone else wants to vote on this or add additional comments I am open to listening.

I vote on this.

**Comment by Plumzie** [comment]
They don't require an item display or anything, just a plain old sign with the item name on it for admin shops.
