### ISSUE TITLE
[BUG] Store resets itself back to an old state

### ISSUE THREAD

**Issue by Plattio** [snowgears/shopbugs#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Data loss

### Environment

```markdown
- Server Version: Paper 1.19 (git-Paper-81)
- Shop Version: 1.8.4.2
```

### Server startup log

Private - No errors found (Dm $plattio#8113)

### Shop config files

https://pastebin.com/wD5AX9di

### Bug description

I have the following problem. A player has created a Sugar Cane Shop which sells 1 piece at a time for 1 coin and there is enough sugar cane, so the sign is green.

Now when I restart the server or reload the plugin, the store sign is reset to an old state. 

Accordingly, it has been marked as sold out here and the quantity has reset to 2. This also happens with the price, if it had been changed. 

However, this bug only occurs with some individual stores and not with all.

Video: https://youtu.be/_YXb9PIAOBY

### Steps to reproduce

The bug cannot be replicated directly, as it only occurs in some stores and the cause is unknown.

Video: https://youtu.be/_YXb9PIAOBY

### Expected behaviour

The store does not reset.

### Actual behaviour

The store resets itself back to an old state.

**Comment by Plattio** [comment]
I have discovered the following errors in the console, which are also often displayed there. Unfortunately, I do not know if it is directly related to the above bug.

```
[12:16:37 ERROR]: Could not pass event InventoryCloseEvent to Shop v1.8.4.2
java.lang.NullPointerException: null
```

**Comment by Kenshin175** [comment]
It's the same for me

**Comment by OstlerDev** [comment]
This issue should be fixed now I believe. If this is still an issue for you please feel free to create a new bug report!
