### ISSUE TITLE
[BUG] Weird error in console

### ISSUE THREAD

**Issue by RainbowTea** [snowgears/shopbugs#391]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: 1.19.3
- Shop Version: Shop-1.8.4.2
- Running Paper version git-Paper-406 when the error occurred. However while sending this report I did update to : Paper version git-Paper-417 
- I don't know if this helps but I am using MYSQL for the shop data.
```

### Server startup log

https://gist.github.com/RainbowTea/be37fc9cabda456eeede41f5b3940865

### Shop config files

https://gist.github.com/RainbowTea/c6ed615345e004e95d9dc848fe6b3463

### Error log (if applicable)

https://gist.github.com/RainbowTea/cc1f1c891792e9992c3281ba895678cb

### Bug description

I don't know what is happening. I see this error in the console occasionally. I don't think it's happening when someone is making a purchase because no one is in our market area when it occurs as far as I can tell through the console. 

### Steps to reproduce

N/A

### Expected behaviour

Expected behaviour is that there are no errors in console.

### Actual behaviour

Errors in console randomly.

**Comment by snowgears** [comment]
Can you download the latest version of 1.8.4.2 from Spigot? There was a patch fix for this a while ago that should fix your issue. The original 1.8.4.2 build had this bug and I removed and reuploaded. Please reopen if this still occurs after that
