### ISSUE TITLE
[BUG] Shops not loading at startup on a server with Slime world format

### ISSUE THREAD

**Issue by iLemon** [snowgears/shopbugs#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: 1.19.2
- Shop Version: 1.8.4.3
```

### Server startup log

https://pastes.dev/q0Gj0wc1YF

### Shop config files

https://pastes.dev/vr2sXvnTma

### Error log (if applicable)

https://pastes.dev/q0Gj0wc1YF

### Bug description

Display holograms and glass cage isn't loading. I have errors in my console, perhaps due to the fact my skyblock server uses slime world format and the worlds aren't loaded on startup?

### Steps to reproduce

n/a

### Expected behaviour

Displays should load.

### Actual behaviour

Displays don't load.

**Comment by iLemon** [comment]
I've realised that this breaks shop loading entirely, so the plugin is non-functional for me.

**Comment by OstlerDev** [comment]
This should be fixed in the latest versions of Shop, if this is still an issue for you, please feel free to reopen this ticket. Sorry it didn't work!
