### ISSUE TITLE
[BUG] Plugin loads but users cant interact

### ISSUE THREAD

**Issue by gerardvanschip** [snowgears/shopbugs#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: git-Paper-18 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 2e363c7)
- Shop Version: 1.8.4.4
```

### Server startup log

https://paste.gg/p/anonymous/32c53095eebd4428b6898fa480db3f17

### Shop config files

https://paste.gg/p/anonymous/3740345ba8d94a52b2f2c84590d2e6b8

### Bug description

All seems to work apart from buying and selling from the shops.

### Steps to reproduce

Go up to a shop and click on the sign to buy or sell.

### Expected behaviour

Items added or removed from my inventory and money exchanged.

### Actual behaviour

Nothing happens when trying to buy or sell

**Comment by alfredcort** [comment]
I can confirm that this is the case for me too

**Comment by alfredcort** [comment]
> Please update to the latest stable version of paper and let me know if this is still an issue. Looks to be an issue with Paper, not with Shop

Hiya,
I updated to the latest version of Purpur and it now works flawlessly. I'm ever so sorry for blaming you :)

**Comment by gerardvanschip** [comment]
> Please update to the latest stable version of paper and let me know if this is still an issue. Looks to be an issue with Paper, not with Shop

Aaaan thats why we love this plugin and its dev! I will close this now as updating to the latest papermc resolved the issue. Thanks for figuring that out.
