### ISSUE TITLE
[Feature Request] Display Coordinates for Shops

### ISSUE THREAD

**Issue by RillSoji** [snowgears/shopbugs#404]
Having a shop directory is fantastic but it's not terribly helpful if you've disabled the warp to shop feature. Especially on a large server with many shops. 

I'd love to see a feature added that simply prints to the chat window the world and coords of the shop when a player clicks the icon that would have normally teleported them. Perhaps an additional config of "Enable coords in chat if warp is disabled: true"  

Alternatively just having the world and coords appear in the tooltip when you hover over the shop icon would also be very helpful. 

Kudos for the awesome plugin. It's the most vanilla feeling shop plugin I've found that is also large-population server friendly. It will help a LOT with both our moderation and shop directory needs if we can get coords for shops added. Thanks!

**Comment by snowgears** [comment]
All shop icons and their display name / lore is able to be customized!

You can have shop icons have the world name and x,y,z coordinates in the lore if you want them!
