### ISSUE TITLE
Could not pass event InventoryClickEvent to Shop v1.8.4.4[BUG] Your Title Here

### ISSUE THREAD

**Issue by ofunny** [snowgears/shopbugs#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: git-Paper-98 (MC: 1.20.1)
- Shop Version: Shop version 1.8.4.4
```

### Server startup log

https://mcpaste.io/b9d32e86f085ee51

### Shop config files

https://paste.gg/p/anonymous/86b7293e6feb483bb00ee2a3f80ca43d

### Bug description

Could not pass event InventoryClickEvent to Shop v1.8.4.4 when somebody opens the shop GUI.

### Steps to reproduce

Actually a player opened the shop's GUI but I could not replicate it myself, maybe you have an idea?

### Expected behaviour

No exception in console

### Actual behaviour

Exception in console

**Comment by OstlerDev** [comment]
This should be fixed in the latest versions of Shop, feel free to log a new bug report if this is still an issue for you!
