### ISSUE TITLE
[BUG] Shop now incompatible with Grief Prevention

### ISSUE THREAD

**Issue by MacTh3Mac** [snowgears/shopbugs#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: Paper 1.20.1 (latest)
- Shop Version: 1.8.4.4
```

### Server startup log

https://github.com/TechFortress/GriefPrevention/issues/2134

### Shop config files

https://github.com/TechFortress/GriefPrevention/issues/2134

### Bug description

Grief Prevention now blocks the interact on shop signs.

We have attempted to have GP reverse the commit that causes the bug, however the author appears to believe that his solution is the correct one. Details here:

https://github.com/TechFortress/GriefPrevention/issues/2134

Please amend shop to either run at at a higher priority, or...  mark the sign as not editable  or wax the signs.   

Any of the 3 solutions will ensure ongoing compatibility.

n.b.  Many other plugins signs are unaffected as they just lower their priority to LOWEST.   this ensures your plugin always handles the interact first.

### Steps to reproduce

click a shop sign in a grief prevention protected claim

### Expected behaviour

interact should be possible to complete a purchase / sale

### Actual behaviour

event is blocked by GP

**Comment by MacTh3Mac** [comment]
GP have now approved a PR https://github.com/TechFortress/GriefPrevention/pull/2142  that resolves the issue partially.   However I would suggest that future **shop** versions specify the iseditable tag.   or potentially  use a iswaxed attribute.   

This would allow a greater compatibility with multiple protection software.

**Comment by OstlerDev** [comment]
I believe this bug has been fixed in the latest versions of Shop. Right clicking a sign does not edit it for me, however I have not tested it out with GriefPrevention. Since this is no longer an issue for you I am going to close this ticket, however if you are still having issues please feel free to log a new bug report!
