### ISSUE TITLE
[BUG] [bungeecord] no money coming in

### ISSUE THREAD

**Issue by adam8014** [snowgears/shopbugs#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: 1.20.1
- Shop Version: 1.8.4.4
- bungeecord : 1726
```

### Server startup log

https://paste.gg/p/anonymous/649b7c95242848cd935f4fb96cbfa3ac

### Shop config files

https://paste.gg/p/anonymous/93bdce477b244d0b8484762d8d027cc3

### Bug description

In a server made up of bungee codes, if the player is not on the server and the item is sold, the money does not come in even if you log in.

### Steps to reproduce

1. create a shop
2. log out
3. others buy things
4. Shop owner logs in
5 .check money

### Expected behaviour

money is not deposited

### Actual behaviour

money is not deposited

**Comment by OstlerDev** [comment]
This issue should be fixed now I believe. If this is still an issue for you please feel free to create a new bug report!
