### ISSUE TITLE
[BUG] Right clicking to pay opens up sign editing.

### ISSUE THREAD

**Issue by RainbowTea** [snowgears/shopbugs#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: This server is running Paper version git-Paper-222 (MC: 1.20.2)
- Shop Version: Shop-1.8.4.5.jar
```

### Server startup log

https://gist.github.com/RainbowTea/e7ca8fe930d6ee114ecdeeb7e40939c4

### Shop config files

https://gist.github.com/RainbowTea/05154c771e7013bb46de47bac02bec1a

### Error log (if applicable)

None as far as I can tell when I make a shop purchase.

### Bug description

Bug: 

Right clicking sign with diamond in hand to make a purchase opens up the sign editing. It never did this before. Item is successfully purchased but sign edit menu should not open.

Video: https://drive.google.com/file/d/1GN6gDLLV5HxfIrotlXUSXN92UipsNIML/view?usp=sharing

### Steps to reproduce

How I tested it:
- Restarted the server just incase a reboot would fix it.
- I deop'd myself
- Made sure I was a newbie rank on my server. 
- Right-clicked a shop sign, item is purchased and in my inventory. However, the right click to edit sign opens up. This has not happened before. It started occurring after I updated our server to 1.20.2.

### Expected behaviour

Players should not be able to edit a shop sign that is not theirs.

### Actual behaviour

Sign editing opens when it should not.

**Comment by MacTh3Mac** [comment]
Similar Issue to #409  The solution to both these issues would be to set the iseditable flag to false or Convert to a waxed sign the moment to shop is actually created. It would however potentially restrict backwards compatibility to older minecraft versions.

**Comment by OstlerDev** [comment]
This has been fixed in my testing, feel free to open a new bug report if this is still an issue for you!
