### ISSUE TITLE
[BUG] Exiting out of the creative window for creating a buy shop breaks chat

### ISSUE THREAD

**Issue by kkshah96** [snowgears/shopbugs#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: Paper 1.20.4
- Shop Version: 1.8.4.6
```

### Server startup log

https://paste.gg/p/anonymous/498566522b784106ba2586b6f9f21575

### Shop config files

https://paste.gg/p/anonymous/1fb5f429db3a413a910ef6436ef9335c

### Bug description

When creating buy shops is disabled for players via permissions, accidentally trying to create a buy shop, then exiting out of the creative menu causes the player to not be able to type in chat until they restart their game

### Steps to reproduce

1. Enable permissions, and only assign the permissions for creating sell shops (not sure if this step is necessary, but is the configuration on my server)
2. Shift left click chest
3. Open creative menu
4. Manually exit out of creative menu without selecting an item
5. Game reverts to survival mode, but nothing can be typed in chat

### Expected behaviour

Chat should be accessible if a player manually aborts creating a buy shop

### Actual behaviour

Chat is not accessible if a player manually aborts creating a buy shop by escaping out of the creative menu

**Comment by BEMZ01** [comment]
Having this issue when using [KawaMood's Waystones datapack](https://modrinth.com/datapack/waystones-data-pack), if a player shift right-clicks the waystone, they get can no longer chat.

**Comment by OstlerDev** [comment]
This bug has been fixed in the upcoming release of v1.9.0.2

**Comment by OstlerDev** [comment]
Released 1.9.1.0
