### ISSUE TITLE
[BUG] GUI Menu Does Not Work with ClickEvents

### ISSUE THREAD

**Issue by Nullifii** [snowgears/shopbugs#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console, Other unexpected behaviour

### Environment

```markdown
- Server Version: Purpur 1.20.6
- Shop Version: 1.9.0.0
```

### Server startup log

https://gist.githubusercontent.com/Nullifii/c19959b1c1e5c299c28218f184bd1878/raw/75aa27ea1d507c5d1f4ba5ee2fe44dc9f07dc29f/gistfile1.txt

### Shop config files

https://gist.github.com/Nullifii/7d1060d7b330d08c37a6ab57d5efc95b

### Error log (if applicable)

https://gist.githubusercontent.com/Nullifii/32b56f2977378045b412302810877f5a/raw/682c075fca3dbaa9c2057355a3d305d8126246e5/message.txt

### Bug description

When trying to use the gui, none of the items in the frame do anything and they throw errors when taking them out of the frame and when putting them back in.

### Steps to reproduce

execute /shop
click on any of the items in the menu

### Expected behaviour

gui should open new menu with correct options

### Actual behaviour

nothing happens and errors are thrown in the console

### Other information

https://spark.lucko.me/XPe3lIVn3y

**Comment by HammontreeArt** [comment]
I have a similar issue.  

Any custom inventory pop-up.   For example,  Essentials Ender Chest command: /ec  or  Player Vaults command:  /pv 1

[20:00:01 ERROR]: Could not pass event InventoryClickEvent to Shop v1.9.0.0
java.lang.RuntimeException: java.lang.IllegalAccessException: class com.snowgears.shop.gui.ShopGUIListener cannot access a member of class org.bukkit.craftbukkit.inventory.CraftContainer$1 with modifiers "public"

https://gist.github.com/HammontreeArt/28dfb056a1f631d4a3d1692aac880f6b
https://gist.github.com/HammontreeArt/8e7e035907fa5a81bd41aea92e45a416

Steps to Recreate: 
1. create a fresh test server with latest version of paper.
2. add Shop and Essentials plugins
3. Start the server 
4. run command /ec
5. click anywhere in inventory.

**Comment by OstlerDev** [comment]
Purpur is not officially supported, please switch to Paper and see if that fixes your issue.

**Comment by MineTommy** [comment]
Same Issue here. Tested with Purpur and Paper 1.21 (Both the Same errors)

**Comment by rodgerturley** [comment]
same issues on spigot 1.21

**Comment by OstlerDev** [comment]
Fixed in 1.9.0.1
