### ISSUE TITLE
[BUG] Shop item displays do not work and fill console with errors

### ISSUE THREAD

**Issue by simondumalski** [snowgears/shopbugs#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console, Other unexpected behaviour

### Environment

```markdown
- Server Version: Paper version 1.20.6-148-ver/1.20.6@20f5165
- Shop Version: 1.9.0.0
```

### Server startup log

https://paste.gg/p/anonymous/995f2b55bb5d4e569309a9133c9e0a7f

### Shop config files

https://paste.gg/p/anonymous/b3dbe3ffea3f4bd085e92c8c45354c0a

### Error log (if applicable)

https://paste.gg/p/anonymous/1f2891d0b7714dc093f47a711c8f1745

### Bug description

When creating a ChestShop, the item display does not function and fills the console with "no such method" errors

### Steps to reproduce

1. Create a shop
2. Console fills with errors

### Expected behaviour

Console does not fill with errors and the item display works

### Actual behaviour

Item display does not work (shop is functional) and console is filled with errors

**Comment by OstlerDev** [comment]
Fixed in 1.9.0.1
