### ISSUE TITLE
[BUG] Shop Plugin Startup Error

### ISSUE THREAD

**Issue by Ste3et** [snowgears/shopbugs#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: 1.21-109-master@5a5035b
- Shop Version: 1.9.0.0
```

### Server startup log

https://mclo.gs/FbQXqO6

### Shop config files

https://gist.github.com/Ste3et/24eb6b351d1493fe0297466a50188967

### Error log (if applicable)

https://mclo.gs/FbQXqO6#L804

### Bug description

A Exception will be throwed on Server Startup with the Default Configs and old PlayerShops

### Steps to reproduce

Start the 1.21 Paper Server and the Error appeared in the Console

### Expected behaviour

The Shop System works

### Actual behaviour

No Issue here only the Error

**Comment by OstlerDev** [comment]
Could you attach the folder containing the old shop files?

**Comment by Ste3et** [comment]
Thank you for your attention you can find them here https://my.hidrive.com/lnk/VLkVSvtfF

**Comment by OstlerDev** [comment]
Can you test Shop 1.9.0.1 and see if it fixes your issue? I tested your configs locally with it and it seemed to work.

**Comment by Ste3et** [comment]
I don't figure it out atm but with the 1.9.0.1 Version it is still present for me:
https://mclo.gs/DNziv0X

**Comment by OstlerDev** [comment]
@Ste3et Please check your itemCurrency.yml file, it looks like there is an issue with it. Try deleting the file and let it recreate itself, that should fix the issue. You can then set your desired itemCurrency again.

Let me know if that fixes it!

**Comment by OstlerDev** [comment]
@Ste3et are you still running into issues with the latest v1.9.1.2 version? I have fixed a bug with our NBTAPI so that it will support "old" materials like your config is using. Please update to v1.9.1.2 and open up a new bug report/reopen this one if it still isn't working.
