### ISSUE TITLE
[BUG] startup error 1.9.0.1

### ISSUE THREAD

**Issue by uldtot** [snowgears/shopbugs#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: 1.21
- Shop Version: 1.9.0.1
```

### Server startup log

https://paste.gg/p/anonymous/add814241411462ea0834e9925cd0b2b

### Shop config files

https://paste.gg/p/anonymous/b545172e5b0a42568391703451b90354

### Bug description

Plugin not loading due to error. 

### Steps to reproduce

-

### Expected behaviour

-

### Actual behaviour

plugin not working

**Comment by OstlerDev** [comment]
Shop 1.9.0.1 does not support Spigot, please switch to using Paper :)

**Comment by uldtot** [comment]
> Shop 1.9.0.1 does not support Spigot, please switch to using Paper :)

Ah, thanks! It worked switching to Paper MC. Thought paper just was a different version and not a replacement of Spigot :)

**Comment by OstlerDev** [comment]
> > Shop 1.9.0.1 does not support Spigot, please switch to using Paper :)
> 
> Ah, thanks! It worked switching to Paper MC. Thought paper just was a different version and not a replacement of Spigot :)

Paper has been very similar to Spigot for a long time (and still is based on spigot at its core), but Paper introduced some large changes in 1.20.6 that move it away from being as compatible with Spigot. So in essence you are correct, it’s mainly just that Paper made some incompatible changes very recently :)

glad you got it working!
