### ISSUE TITLE
[BUG] Shop not working

### ISSUE THREAD

**Issue by Lorafen223** [snowgears/shopbugs#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: paper-1.21-123
- Shop Version: Shop-1.9.0.1
```

### Server startup log

https://gist.github.com/Lorafen223/42bcad4bcf894c362aa978d0d681c5b2#file-gistfile1-txt

### Shop config files

default config files

### Bug description

Rightclicking on shop sign does nothing. Same with selling as with buying in admin shops.

### Steps to reproduce

Create basic server with the plugin, (tried emerald currency).

### Expected behaviour

Should get the item when rightclicking on the sign.

### Actual behaviour

Nothing happens

### Other information

![2024-08-01_21 52 28](https://github.com/user-attachments/assets/0cfb8acb-28ee-483c-942d-ae6ea53f0fd3)

**Comment by OstlerDev** [comment]
![IMG_1695](https://github.com/user-attachments/assets/57649959-d46d-4fee-a175-76928a80aeef)
Closing at request of user.
