### ISSUE TITLE
[BUG] checkItemDurability flag broke shops

### ISSUE THREAD

**Issue by Shepelzz** [snowgears/shopbugs#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Bug

### Environment

```markdown
- Server Version: 1.21
- Shop Version: 1.9.0.1
```

### Server startup log

https://paste.gg/p/anonymous/4b4dcb34f96a440d8772507c69490ff4

### Shop config files

https://paste.gg/p/anonymous/f505ea1c9481418d84c034214e289b63

### Bug description

When i set checkItemDurability to FALSE, all my existing shops are out of stock, no matter is there enough stock or not.

### Steps to reproduce

1. Run plugin with checkItemDurability: true
2. Create sell stone shop and fill chest with stone. Shop is "green"
3. Change checkItemDurability to false and reload plugin or server.
4. try to look into your chest and shop will be updated as out of stock.

### Expected behaviour

Shop should work

### Actual behaviour

Shop not works

**Comment by Shepelzz** [comment]
@snowgears any response?

**Comment by OstlerDev** [comment]
I will look into this, it is likely an issue with the NBT data changes in 1.21. Hopefully this fix will be included in v1.9.0.2, otherwise it will likely be in v1.9.0.3

**Comment by OstlerDev** [comment]
Verified and Fixed in upcoming release 1.9.1.0
