### ISSUE TITLE
[BUG] Plugin wont load on 1.21.1 and when switching back wont load on 1.21

### ISSUE THREAD

**Issue by gerardvanschip** [snowgears/shopbugs#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Versions: 1.21 build 4289
- Server Versions: 1.21.1-R0.1-SNAPSHOT (trying both, just in case)
- Shop Version: Shop-1.9.0.1.jar
```

### Server startup log

https://gist.github.com/gerardvanschip/5feb7c8825429309f96a55c47d904981

### Shop config files

https://gist.github.com/gerardvanschip/1243f85ce2f284196d8dbfc1f6e7b7ad

### Bug description

The plugin was working with 1.21 (10 versions or so behind) I then updated to 1.21.1 and it stopped working. Going back to 1.21 sadly did not fix it. Starting with a fresh config did not resolve it. It simply wont load. No shops function.

### Steps to reproduce

1. Start server
2. Notice error in the log
3. try to create or otherwise interact where a shop used to be

### Expected behaviour

Loading and working.

### Actual behaviour

Error both in log and in game.

**Comment by OstlerDev** [comment]
Are you using Paper? If you are running Spigot please use 1.9.0.0, if you are running Paper please use the latest version of 1.9.0.1. Only Paper will be supported going forward (for now).

**Comment by OstlerDev** [comment]
I just took a look at your logs again, it looks like you are using Spigot and not Paper. Please switch over to PaperMC or use v1.9.0.0 for Spigot support. I am going to close this issue, but feel free to reopen it if you run into some other issue.
