### ISSUE TITLE
Add admin commands to remove player shops

### ISSUE THREAD

**Issue by DofyAdmin** [snowgears/shopbugs#45]
**Is your feature request related to a problem? Please describe.**
Yes, 
I'm using the plugin AreaShop and when a player unrent his plot everything is reset on the plot, but the shop on it aren't remove and there is no admin command or player command to remove a shop at distance.

**Describe the solution you'd like**

Just a command like 
/shop remove <player> <shop>

**Comment by snowgears** [comment]
I like it. 👍

**Comment by DofyAdmin** [comment]
When do you think you will add this option ? ^^

**Comment by snowgears** [comment]
Could be cool to utilize WorldEdit API and remove all shops in selected region as well.

**Comment by snowgears** [comment]
Closing and merging into #266
