### ISSUE TITLE
NullPointerException prevents every item display

### ISSUE THREAD

**Issue by Rossmall** [snowgears/shopbugs#46]
Hello and thank you for maintaining this plugin !

**Describe the bug**
On server startup, these five exceptions are raised, and none of the ~400 shops in the server display items.
https://pastebin.com/cyxkJCeV

I know that some parts of the world where edited using WorldEdit, and some shop signs might have been deleted or buried without a proper remove.

**Expected behavior**
If it's possible, it would be good to have logs about which shop (world+coordinates) is causing these exceptions, so I can teleport there and remove the culprits.
Furthermore, it would be even better that a few buggy shops don't prevent all other shops from displaying items.

**Version:**
 - Spigot version: Spigot 1.13.2
 - Shop version 1.8.0.1

**Comment by BillyGalbreath** [comment]
Fixed in next release
