### ISSUE TITLE
[BUG] NBT issue with barter shops 

### ISSUE THREAD

**Issue by Hustle767** [snowgears/shopbugs#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: 1.21.1
- Shop Version: Dev 1.10.0
```

### Server startup log

https://pastebin.com/yrEPhFsu

### Shop config files

https://pastebin.com/MjhZsSu4

### Error log (if applicable)

N/A

### Bug description

When "ignoreItemRepairCost: true"
Yes it Allows  for Sales Same Item but Different NBT "repair-cost" 
but i also completely ignores NBT Data being received as currency from a barter shop which has become an issue for me.

For example:
I create a barter shop that sells Unique Mob heads and takes special tokens as currency.
These tokens are golden nuggets named "Shop Token" with Loyalty 1 enchantment on it made with this vanilla command: 
/minecraft:give @p gold_nugget[custom_name='["",{"text":"Shop Token","italic":false}]',enchantments={levels:{loyalty:1}}]

Making the barter shop is fine but when purchasing from the shop you can simply use regular, un enchanted default golden nuggets to purchase instead of specifically the same enchanted custom golden nugget.

### Steps to reproduce

1. Create barter shop that is meant to sell players... anything really in this case we are selling mob heads and other hard to obtain items.

2. Use a custom/nbt applied item as the currency the shop is meant to receive. In this case we are trying to use custom golden nuggets with the Loyalty 1 enchant added since this cant be obtained normally only through command/creative.
/minecraft:give @a gold_nugget[custom_name='["",{"text":"Shop Token","italic":false}]',enchantments={levels:{loyalty:1}}]

3. Now give your self regular, default golden nuggets and try to use the barter shop that should only expect custom loyalty 1 nuggets and it will purchase with the default ones no problem.

When "ignoreItemRepairCost: false" this issue doesn't happen.

### Expected behaviour

The barter shop should only accept the same custom loyalty 1 golden nugget as currency not just any golden nugget.

### Actual behaviour

Any golden nugget can be used to purchase from the barter shop

### Other information

I was hoping this could get fixed specifically for the barter shops because I like having When "ignoreItemRepairCost: true" because it lets users sell swift sneak 3 books easier, enchanted elytras ect but also have setup custom vip shopping areas that use those custom golden nuggets as currency instead of our default diamonds.

**Comment by OstlerDev** [comment]
Fixed in dev commit 98c0bc5
