### ISSUE TITLE
[BUG] MySQL leak/connection issues?

### ISSUE THREAD

**Issue by Hustle767** [snowgears/shopbugs#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: 1.21.1
- Shop Version: 1.10.0 dev
```

### Server startup log

https://pastebin.com/yrEPhFsu

### Shop config files

https://pastebin.com/MjhZsSu4

### Error log (if applicable)

https://pastebin.com/x5MbHADT & https://pastebin.com/QHPQvhAh

### Bug description

One specific player attempted to make a shop one night and this started getting spammed in console: https://pastebin.com/x5MbHADT At first I didn't know what the issue was, the server tps dropped to 5 and It couldn't stabilize for a while. It happened 3 nights in a row till I was able to diagnose when it was happening. 
Offline notifications as well were not working in this build which im assuuming is all related to the same mysql leak / issuue. As soon as I turned off MYSQL I stopped having errors and massive tps drops when that player tried to create a shop

### Steps to reproduce

Honestly I'm not sure how I would reproduce this since it took so long to figure out the cause other than something related to mysql. 
First off by turning on MYSQ you'll see offline notifications and other related mysql features are not working

### Expected behaviour

Player should of been able to create shop,
TPS should be fine, no mysql errors

### Actual behaviour

Player cannot create shop
MYSQL spits huge errors in console
Server dumb thread and tps drops to 5 if not server crashes completely.

**Comment by OstlerDev** [comment]
I just rewrote the LogHandler in the dev version, I will send you over the latest build to verify! Closing this for now though :D
