### ISSUE TITLE
[BUG] Cant create shulker shells sell shop

### ISSUE THREAD

**Issue by Hustle767** [snowgears/shopbugs#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: 1.21.1 paper
- Shop Version: dev 1.10.0
```

### Server startup log

https://pastebin.com/Yce7dTnR

### Shop config files

https://pastebin.com/HAmdcLQ9

### Bug description

Cannot create a shop that sells shulker shells

### Steps to reproduce

1. Create a sell shop for shulkers shells only
2. Shop wont be created properly
3. If someone else hits the sign to buy it just opens up sign editing interface
4. Error output in console: [13:15:25 ERROR]: Could not pass event InventoryCloseEvent to Shop v1.10.0

### Expected behaviour

regular sell shop of shulkers should be created

### Actual behaviour

No shop is created just a broken chestshop with sign that can be edited.

**Comment by OstlerDev** [comment]
Fixed in dev commit 61a7b4e
