### ISSUE TITLE
Delete player shops who have not logged in after x amount of time

### ISSUE THREAD

**Issue by johnsoncui02** [snowgears/shopbugs#48]
So currently I have a rent region for AreaShop, and if the shop time runs out it wipes the region, but the shops that players have created are still there. Is there a way where we can add a inactive purge function so players who are inactive automatically have their shops being "removed" from the plugin? Thanks.

**Comment by snowgears** [comment]
I like this idea. Currently, shop are saved by UUID in the file system so you can also do it manually now if you know what players you want to remove. But I like this idea and will add it soon. Thanks!

**Comment by snowgears** [comment]
Added in 1.8.2.2 (still in development)

`# This will permanently delete a player's shops if they have not logged onto the server after X hours #
# Set this to 0 to never auto-delete a player's shops #
deletePlayerShopsAfterXHoursOffline: 0`
