### ISSUE TITLE
Shop not working properly for enchanted items

### ISSUE THREAD

**Issue by blek-id** [snowgears/shopbugs#49]
**Describe the bug**
Items with enchantments can't be sold on the Shop. It just says out of stock.

**To Reproduce**
1. Create sell or buy shop
2. Place the enchanted item inside the chest
3. Have someone else buys it
4. Shop out of stock

**Expected behavior**
Player could buy the item because the item is in stock

**Version:**
 - Spigot version: Paper 1.13.2
 - Shop version: 1.8.0.1

**Comment by blek-id** [comment]
Change of way to reproduce the problem.

1. Create sell shop
2. Place item inside the chest
3. Player can still buy the item

4. Restarts the server
5. Item is no longer available even though item is still inside

**Comment by snowgears** [comment]
could not recreate in MC 1.16 as I am going through bugs to include in update. Updating Spigot dependencies may have fixed this. Please reopen if Shop 1.8.2 does not fix this bug.
