### ISSUE TITLE
Item Names/1.14 Support

### ISSUE THREAD

**Issue by hamcoremusic** [snowgears/shopbugs#51]
**Is your feature request related to a problem? Please describe.**
I have not yet tried to use this plugin on 1.14, but I would gather that since there are different sign types, it may need an update. Also, it's kind of frustrating when the item names aren't working since 1.12.

**Describe the solution you'd like**
Please provide a 1.14 update complete with all of the item names fixed!

**Describe alternatives you've considered**
I have no alternatives to this solution. Technically you could just give us a list of item names converted for 1.13/1.14 and we can add them to the config.

**Comment by BillyGalbreath** [comment]
Fixed in next release
