### ISSUE TITLE
Need Signs Update cause 1.14.1

### ISSUE THREAD

**Issue by KlenerTeufel96** [snowgears/shopbugs#52]
First Problem: 
The signs were update in 1.14 again and now you need to specified the signs like acacia_sign otherwise he dont find the sign.

Second Problem:
If a player has more than 36 shops and you open the /shop gui, he cant find the item 'STAINED_GLASS_PANE'. You cant teleport to shops or change the sites in the gui.

 Spigot version:  Paperspigot 1.14.1
 Shop version: 1.8.0.1

**Comment by KlenerTeufel96** [comment]
Does something happen here? I think I'll use a more active plugin...

**Comment by BillyGalbreath** [comment]
Fixed in next release
