### ISSUE TITLE
I can't use and create a store

### ISSUE THREAD

**Issue by smallcanner** [snowgears/shopbugs#55]
**Describe the bug**

**To Reproduce**
1. Arrived at my server
2. I use /shop
3. I saw that he said that he could not execute and could not create a store.

**Expected behavior**
I hope we can solve this problem and let me create a store.

**Screenshots**
https://user-images.githubusercontent.com/49681870/59144935-81e63100-8a0f-11e9-9185-fc3d04b4102f.png

https://user-images.githubusercontent.com/49681870/59144962-d093cb00-8a0f-11e9-9879-dd7e55ec3b50.png

https://user-images.githubusercontent.com/49681870/59144964-e99c7c00-8a0f-11e9-921e-1a52679de948.png
**Version:**
 - Spigot version: Spigot - 1.12.2
 - Shop version : 1.8.0.1

**Additional context**
No.

**Comment by snowgears** [comment]
Please provide additional logs from the server with the stack trace. I have no idea what could have caused this error without that.
