### ISSUE TITLE
Ease of Use Enhancement

### ISSUE THREAD

**Issue by hamcoremusic** [snowgears/shopbugs#57]
As I have now heard that 1.13+ support is being worked on, I wanted to take the chance to suggest a feature.

I think it would be a great idea if a player just had the option to create a shop by **hitting the item** off of a chest. This would be a similar setup to QuickShop. I find this is a very approachable way to make a shop for all types of players!

**Comment by BillyGalbreath** [comment]
I dont understand. You can already create a shop by hitting the sign with an item in hand

**Comment by hamcoremusic** [comment]
I'll try to explain it as best as I can.

So let's say a lace a chest, it would be cool to hit the item that you are selling/buying/bartering against the chest to activate a chat UI or a GUI where you can click/type what you want to do.

For example:

1. Place chest
2. Hit the item I'm selling on the chest
3. Sign appears on chest and in chat it asks "What would you like to do with this item? BUY, SELL, or BARTER"
4. After entering/clicking what you want to do, it will ask what price you are BUYING or SELLING for, or what ITEM you are bartering (if it's a barter chest, then it should ask the item and then the amount)
5. The sign will auto-generate and the shop is open.

Again, referencing the original post, it is similar to the QuickShop plugin on Spigot!

**Comment by snowgears** [comment]
Will revisit if necessary but this seems to just want to create shops in a way that involves more chat than signs. Shop is meant to be a sign based plugin.
