### ISSUE TITLE
1.14 Not working

### ISSUE THREAD

**Issue by VirgilFabre** [snowgears/shopbugs#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Spigot version: [e.g. Spigot 1.13.2, Paper-Spigot 1.12.1, etc]
 - Shop version [e.g. 1.7.3.2]

**Additional context**

**Comment by BillyGalbreath** [comment]
Invalid.

**Comment by VirgilFabre** [comment]
What happened to all I typed, I event pressed Preview before sending it...
