### ISSUE TITLE
ERROR Error occurred while enabling Shop v1.8.1

### ISSUE THREAD

**Issue by silvasky54** [snowgears/shopbugs#63]
**Describe the bug**
I get the following error when using the latest version of shop. 

`14.08 17:51:23 [Server] ERROR Error occurred while enabling Shop v1.8.1 (Is it up to date?)
14.08 17:51:23 [Server] INFO java.lang.NoSuchFieldError: BARREL
14.08 17:51:23 [Server] INFO at com.snowgears.shop.handler.ShopHandler.<init>(ShopHandler.java:62) ~[?:?]
14.08 17:51:23 [Server] INFO at com.snowgears.shop.Shop.onEnable(Shop.java:244) ~[?:?]
14.08 17:51:23 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [Spigot_Latest_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
14.08 17:51:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]`

**To Reproduce**
Use Spigot 1.13.2
Update to latest version of shop.

**Expected behavior**
Should continue working like the previous version

**Screenshots**

**Version:**
 - Spigot version: Spigot 1.13.2
 - Shop version 1.8.1

**Additional context**
I'm assuming this update was meant to work on 1.13.2 too and not just a 1.14 update.

**Comment by silvasky54** [comment]
https://pastebin.com/W81QKxEk

A pastebin for the error because githubs code block looks horrible

**Comment by BillyGalbreath** [comment]
You're attempting to use the 1.14 version on a legacy server. Download the plug-in version that supports your server version (1.8.0.1)

**Comment by silvasky54** [comment]
Will there be an update to fix the errors with 1.8.0.1? Ideally having the latest version compatible with 1.13.2 would help so many people. Or atleast a better working version of 1.8.0.1

**Comment by BillyGalbreath** [comment]
No. No one has the time to keep backporting fixes to legacy software. I know it sounds mean/rude, but as a server admin that chose to use a legacy server version you must keep in mind this means you will be using legacy versions of plugins as well.
