### ISSUE TITLE
Item name feature.

### ISSUE THREAD

**Issue by ghost** [snowgears/shopbugs#64]
Hello.

I would like to ask you if you can add a feature to translate item names?
(In the older Shop plugin I can change items.tsv but in the newest version it does not works.)

I think the best way could be the LangUtils: https://github.com/NyaaCat/LanguageUtils/tree/1.14

**Comment by BillyGalbreath** [comment]
Item names are now pulled directly from the language system if using Paper server. If you use Spigot server item names are converted from their API names (often not correct). It is recommended to use Paper server to ensure the correct names are used.

**Comment by Misyoke** [comment]
Is there any way to translate / change them in Paper?
