### ISSUE TITLE
Invalid Item Problem

### ISSUE THREAD

**Issue by TheRealPixit** [snowgears/shopbugs#65]
**Describe the bug**
When hovering over the item when getting more info about a shop it displays "Invalid Item" in red.

**To Reproduce**
1. Make a shop.
2. Put any item in it.
3. Crouch and right click it to get the info.
4. It produces the text when hovering over the item name.

**Expected behavior**
To show any enchantments on it, nbt tags, descriptions, ect.
**Screenshots**
![2019-08-20_18 31 02](https://user-images.githubusercontent.com/34843193/63391614-adbf5480-c378-11e9-8680-4eff9d6251e5.png)

**Version:**
 - Spigot version:1.14.2
 - Shop version [e.g. 1.8.1]

**Additional context**
None.

**Comment by snowgears** [comment]
This should be fixed in the latest update (1.8.2). Please reopen the ticket if this bug persists!
