### ISSUE TITLE
Shulker box duplication bug

### ISSUE THREAD

**Issue by Blurkeon** [snowgears/shopbugs#68]
Users duplicate selling shulker box, I need a way to block the sale of shulkerbox in stores.

**Comment by snowgears** [comment]
how are users duplicating shulker boxes this way? More info would be helpful. Leaving open for now

**Comment by snowgears** [comment]
Still have heard nothing on this. I still am not sure how you were able to duplicate selling. If no info is provided, I will have to close this.

**Comment by snowgears** [comment]
Closing due to no response. Please reopen if anyone can explain how a duplication of items can occur using shulker boxes.
