### ISSUE TITLE
Gamble shop - wrong item amount in win message

### ISSUE THREAD

**Issue by NewBestX** [snowgears/shopbugs#70]
**Describe the bug**
When you win any itemstack from a gamble shop, the amount is always 1: "item_name(x1)"
Value is [gamble item amount] in chatConfig.

**To Reproduce**
1. Make a gamble shop
2. Add a stack of stone and a stack of dirt
3. Gamble...
4. Message says you won x1 of the item, when in fact you won 64.

**Expected behavior**
Message saying you won the right amount.

**Version:**
 - Paper 1.14.4
 - Shop version 1.8.1

**Comment by snowgears** [comment]
This has been fixed in Shop 1.8.2
