### ISSUE TITLE
Null Pointer Exception with gamble shops

### ISSUE THREAD

**Issue by NewBestX** [snowgears/shopbugs#71]
**Describe the bug**
If you only place one item in a gamble shop, or you place multiple items but leave the first slot of the chest empty, it will spit out a NPE to the console and make the shop unusable [until a restart or reload, or until you remake the shop].

**To Reproduce**
1. Make a gamble shop with an empty chest
2. Place only one item in it
3. Close the inventory GUI
OR
2. Place multiple items, but leave the first slot empty
OR
2. Place multiple items
3. Close the chest
4. Open it again
5. Remove all items
6. Close the chest

**Expected behavior**
When left empty, it should revert to the default "any item" behavior.
When there are still items in the chest, it should find those and choose from them.

**Version:**
 - Paper 1.14.4
 - Shop version 1.8.1

**Additional context**
While in this bugged state, chests will spit NPE on interact with the signs, on closing the inventory and on command: /shop item refresh. If a player tries to use the shop, the money will be taken but he won't receive any prize.

Here is the error on interact: https://pastebin.com/2058qtZ4

**Comment by snowgears** [comment]
Fixed in latest update (1.8.2 - still in progress)
