### ISSUE TITLE
Currency Override for Specific Shop

### ISSUE THREAD

**Issue by stageosu** [snowgears/shopbugs#72]
**Is your feature request related to a problem? Please describe.**
I would love to see a feature where, a specific shop's currency can be overridden. I use Vault as the server's currency for all shops, but there is one shop that I want to make an exception for.

**Describe the solution you'd like**
I would utilize this feature to allow for weekly vote rewards. I would give a user a unique item that they can't obtain anywhere else in the world (shulker shell for example) as a weekly reward. Then I would create a gamble shop where they can "gamble" one shulker shell for a cool reward. Currently, I can only gamble the Vault currency.

**Comment by snowgears** [comment]
I do like this idea but it will most likely not be added at this time.

I may revisit it though. I do like it I'm just not sure if more than you would be able to utilize it.
