### ISSUE TITLE
Towny Integration

### ISSUE THREAD

**Issue by Dracathio** [snowgears/shopbugs#75]
**Is your feature request related to a problem? Please describe.**
Welp the problem is Towny Shop plots aren't viewed as a World Guard region, thus towny server owners can't enforce shop plots only concepts.

**Describe the solution you'd like**
Have a section of the code use the ShopPlotUtil from towny to make the plugin work with towny's shop plots.

**Describe alternatives you've considered**
Welp alternatives are out dated plugins that aren't updated to 1.14.4 or aren't of the fun concept of your plugin.

My only other choice is to make my own bridge plugin, that bridges Shop and Towny together. Sadly it would still require me to have a 2nd plugin that turns all towns into world guard regions, thus enforcing the world guard region concept... but it would also mean forcing those towns to become shop regions.  So.... yea a total pain to be honest lol.

**Additional context**
Probably have the true/false setting right under the worldguard setting in the config.
Hopefully you're able to get this set up in a decent time table, but I understand if it's not possible to get it set up right away.

Thank you for considering to work on it.

**Comment by Dracathio** [comment]
Glad to know others want this just as much as I do ^,..,^

**Comment by snowgears** [comment]
Per Managering in discord:

> Request:
Add a towny hookin that allows to set a limit per town level in towny advanced.
Explain:
Towny has multiple town levels. Per an x number of residents, a town can level up. Each level up grants them a new town name, and other things such as more claim blocks etc.
I'd like to request a feature to limit the amount of chestshops to a town. So a one person town gets 20 chestshops. A 5 person town a 50 etc.

**Comment by snowgears** [comment]
Towny support added in 1.8.2.5 (in progress)

New hookTowny variable in the main config.yml that if true, players will only be able to build shops where they are a towny resident
