### ISSUE TITLE
AbstractShop is null

### ISSUE THREAD

**Issue by Creepios** [snowgears/shopbugs#76]
**Describe the bug**
API: Get a AbstractShop from Location (Location is CHEST!) is null!

**To Reproduce**
1. Get Instance of Shop
2. Get ShopHandler
3. getShop(Location)
4. Make anything with the shop variable and See the error (NullPointerException)

**Version:**
 - Spigot version: 1.14.4
 - Shop 1.8.1

**Comment by tWizT3ddreaMr** [comment]
I know it is a bit late of a reply. Are you putting the chest location, or sign location.
I think the from chest is getShopByChest(loc)

**Comment by snowgears** [comment]
@tWizT3ddreaMr is correct
