### ISSUE TITLE
Players can't teleport to shop

### ISSUE THREAD

**Issue by Cawleeflower** [snowgears/shopbugs#77]
**Describe the bug**
i gave the permission node shop.gui.teleport and they cant teleport

**To Reproduce**
give players permission node shop.gui.teleport and they cant teleport 

**Expected behavior**
They can teleport to shops

**Version:**
 - Spigot version: [Spigot 1.14.4]
 - Shop version [1.8.1]

**Additional context**
Click on players item and does not do anything, does not teleport, does not say anything in chat

**Comment by snowgears** [comment]
Please make sure you have the usePerms variable within shop's config set to true as well
