### ISSUE TITLE
Shops can revert if the shop owner changes username.

### ISSUE THREAD

**Issue by markusew** [snowgears/shopbugs#79]
The storage files for the shop chests contain both current minecraft name and UUID of the player. If a player has shop chests under the name, lets say, abc123 and later changes name to xyz987 the shop chests created with the name abc123 will never be removed from the storage file since the users new name is xyz987. 
This means that if another player is attempting to place a shop chest in the same location as the abc123 users shop chest were, it will keep reverting back to abc123's shop chests cause it has a older date and the only way to fix this is to manually edit the storage file.

I recommend for the storage to be changed to UUID only so that this bug cannot occur

**Comment by snowgears** [comment]
This was fixed in Shop 1.8.2
