### ISSUE TITLE
Creation Cost is doubled

### ISSUE THREAD

**Issue by BlisteringSyko** [snowgears/shopbugs#8]
Hello,

When setting creationCost: in config.yml to anything above 0 the cost in game is doubled from the value set. So setting it to 1 consumes 2 items, setting it to 2 consumes 4.

Edit: forgot to mention this is on a Paper 1.13.2 server, build  486 (1.13.2-R0.1-SNAPSHOT)
Thanks

**Comment by snowgears** [comment]
Having trouble recreating this in 1.8.2.1. Please reopen this report if the issue persists after upgrading to shop 1.8.2.1
