### ISSUE TITLE
Question about InventoryMoveItemEvent that Shop listens for

### ISSUE THREAD

**Issue by Teriuihi** [snowgears/shopbugs#85]
According to the timings report paper generates, Shop is causing a lot of lag while listening to the InventoryMoveItemEvent for hoppers. What does it listen for and why would it cause this amount of lag?

I'm running the plugin on 1.15 git-Paper-33 and Shop version 1.8.1

![image](https://user-images.githubusercontent.com/38841986/72117694-f4751180-334e-11ea-88c9-6501650f792d.png)

**Comment by snowgears** [comment]
Shop has to listen to this event because otherwise people would be able to steal items from other players shops using hoppers. Im not sure why it would cause significant lag however.

**Comment by Teriuihi** [comment]
Does it listen for every hopper or just hoppers below containers that are in use by Shop?

**Comment by Teriuihi** [comment]
Does Shop check for pistons pushing chests/shulkers etc? And if so would it be possible to make that a configurable option as well?

**Comment by Teriuihi** [comment]
Would it be possible to add the config option to disable these checks (or this check if the piston one doesn't exist). I would like to keep using the Shop plugin but if this isn't fixed or disabled I will have to switch to another one. I can't afford to keep it with the amount of lag it is causing.

**Comment by BillyGalbreath** [comment]
Plugins don't cause lag from events. If you are experiencing lag from the `InventoryMoveItemEvent` from hoppers, there is a setting in paper.yml (Paper servers only, not Spigot) to disable that event. Beware, disabling that event will prevent any protection plugins listening to it from protecting it.

**Comment by Teriuihi** [comment]
Forgot to respond to this, I've disabled the InventoryMoveItemEvent as you suggested and it has helped quite a bit. Thanks for your help!
