### ISSUE TITLE
Plugin not enabeling

### ISSUE THREAD

**Issue by AggerTV** [snowgears/shopbugs#86]
**Describe the bug**
I'm not sure, the plugin just isn't enabled

I'll attach the latest log, so you can see if there's anything there.

**Screenshots**

https://gyazo.com/0ddc981542880c0a602dce4a9ed25d19

**Version:**
 - https://gyazo.com/fc273e386954159344b6e9ce4ebac47b
 -https://gyazo.com/bebccd5ef9c7bd1af2a657c45afaedda

[latest-log.txt](https://github.com/snowgears/shopbugs/files/4112688/latest-log.txt)

**Comment by TechnoRunner18** [comment]
I believe you have the wrong server log because it does not mention the shop plugin anywhere. However, if you are running minecraft 1.12.2, use Shop version 1.7.3.2 from **[HERE](https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/download?version=209737)**
