### ISSUE TITLE
bug with display item

### ISSUE THREAD

**Issue by AggerTV** [snowgears/shopbugs#87]
**Describe the bug**
If you break the chest, the display item will drop to the ground, and you will not be able to pick up the item

**To Reproduce**
1. create a shop
2. break the chest under the display item

**Expected behavior**
The display item should be removed instantly, when you remove the chest.

**Screenshots**
https://gyazo.com/20f46b74d980ef291c932b62fe50a342

**Version:**
 - Spigot version: [e.g. Spigot 1.13.2, Paper-Spigot 1.12.1, etc]
 - Shop version [e.g. 1.7.3.2]

https://gyazo.com/81940e441becd482074a91d0f6fbc039

**Additional context**

**Comment by ProsperCraft** [comment]
We do not have this problem on 1.12.2 using Mohist to merge spigot and forge.
Shop1.7.3.2
Mohist-2b0299e-server

**Comment by ProsperCraft** [comment]
We use
# This will change the types of displays that shops will use above their chests #
# The options are: NONE, ITEM, GLASS_CASE, LARGE_ITEM #
displayType: LARGE_ITEM

Because these are not affected by modded magnets.

**Comment by AggerTV** [comment]
Okay, but what would i need to do to fix the issue?

**Comment by ProsperCraft** [comment]
Try setting the config option like we did to use the LARGE_ITEM type.

**Comment by AggerTV** [comment]
I did as you said, but still it isn't fixed.

Also, should players even be able to mine an active shop???

**Comment by ProsperCraft** [comment]
No mine can't, you have something fundamentally wrong with your setup.

**Comment by AggerTV** [comment]
signConfig.yml:
https://pastebin.com/8571xnMC

items.tsv
https://pastebin.com/FYqSMEsc

guiConfig.yml:
https://pastebin.com/vHwJ2Ygy

config.yml:
https://pastebin.com/bR8pKiCE

chatConfig.yml:
https://pastebin.com/kSmmb6Nm

**Comment by AggerTV** [comment]
Have you spottet an error in the files provided in the above comment?

**Comment by AggerTV** [comment]
Please respond

**Comment by snowgears** [comment]
Shop chests should not be able to be broken without first breaking the sign. Tested on latest version. If you feel this is still an issue please open another ticket.
