### ISSUE TITLE
The hologram is showing XXX < - -60,64,-64) x1

### ISSUE THREAD

**Issue by MCMaricopaAZ** [snowgears/shopbugs#88]
**Describe the bug**
 The hologram is showing XX(< - -60,64,-64) x1 (see screenshot)

**To Reproduce**
1.  Install ServerBooster
2. place a chest 
3. add a shop sign 
4.  See Screenshot

**Screenshot:**
https://s3.amazonaws.com/files.enjin.com/1744413/2020-02-02_21.19.01.png

**Version:**
Server: Paper-Spigot 1.15.2
Host: Server Minor

**Conflicting Plugin:** 
https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-serverbooster-%E2%9A%A1optimize-your-server-anti-lag-fps-boost-multilanguage%E2%9A%A1.72184/

**Additional context**
LoneDev said ask you...... ask plugin author to add a setting to set custom name visible = false.  You can send him this plugin link as ServerBooster is compatible with it: 
https://github.com/Ghost-chu/QuickShop-Reremake/blob/b605475b33676d45fab2ac35a52f85a5f1e2923e/src/main/java/org/maxgamer/quickshop/Shop/RealDisplayItem.java#L196

**ServerBooster Thread**
https://www.spigotmc.org/threads/%E2%9C%85must-have%E2%9C%85-serverbooster-%E2%9A%A1optimize-your-server-anti-lag-fps-boost-multilanguage%E2%9A%A1-paid.401071/page-3#post-3678988

I am able to work around it.  Your  plugin has 3 different modes to choose from and 1 of the display modes works. Of course, the other 2 modes are what players really like.  

B.Rgds,
MCMaricopaAZ

**Comment by MCMaricopaAZ** [comment]
I'm using SHOP v1.8.1
Server Log - https://pastebin.com/05hz3zKZ

**Comment by snowgears** [comment]
this is another plugin showing the title of the display. to fix this please reach out to that developer and they can use Shop's API to hide these items that they are currently showing
