### ISSUE TITLE
Double shopdata after namechange

### ISSUE THREAD

**Issue by martijnpu** [snowgears/shopbugs#89]
**Describe the bug**
At the moment a players changes their name a new datafile will be generated with the new name, but the old one will not be removed. This cause the problem that changes to shopssigns will be reverted to the old ones of the old name.

**To Reproduce**
Create a shopsign
Change your minecraftname (but hold the same UUID)
Delete/change the shopsign
Reload the plugin/Restart the server

**Expected behavior**
The old sign is back

**Version:**
 - Paper 1.5.2 (build 81)
 - Shop version1.8.1

**Additional context**
You're doing great to detect a namechange, but you forgot to remove the old file.

**Comment by SiuanSong** [comment]
Duplicate bug report
https://github.com/snowgears/shopbugs/issues/53

**Comment by james090500** [comment]
This is still an issue, unfortunately. 

I understand this is the premium plugin and the devs are probably busy with their lives. would you consider passing this to someone who can maintain it?

**Comment by snowgears** [comment]
This was fixed in Shop version 1.8.2
