### ISSUE TITLE
Add support for viewing enchantments on Enchanted Books being sold!

### ISSUE THREAD

**Issue by CilantroLeaver** [snowgears/shopbugs#91]
I love the functionality of this plugin in regards to displaying a hologram of the item being sold above the chest. However, there is no way to view the enchantment on an enchanted book being sold upon just looking at the hologram. Please add a way to see the enchantments you are purchasing!

**Comment by BillyGalbreath** [comment]
Click chest for details in chat of what's being sold. Hover mouse over item in chat to see fine details like that

**Comment by CilantroLeaver** [comment]
When I hover in chat, nothing displays. Only "Enchanted Book".

**Comment by snowgears** [comment]
![2020-08-19 21_39_57-Window](https://user-images.githubusercontent.com/4141199/90710734-9d300b80-e264-11ea-8449-486ed521bffe.png)
This appears to be working in Spigot 1.16.1 and Shop 1.8.2. Closing issue.
