### ISSUE TITLE
Can't use numbers like 0.1,0.2,0.3

### ISSUE THREAD

**Issue by DofyAdm** [snowgears/shopbugs#93]
**Describe the bug**
Hi !
I would like to use numbers like 0.5, 0.25...
But for the plugin these numbers are not positive ; /

**Expected behavior**
Complete the creation of the shop normally.

**Screenshots*
Not usefull

**Version:**
 - Spigot version: 1.14.4
 - Shop version: 1.8.1

**Comment by snowgears** [comment]
This was fixed in Shop 1.8.2
