### ISSUE TITLE
NoSuchFieldError on startup/shops not working in-game

### ISSUE THREAD

**Issue by Verbannt** [snowgears/shopbugs#94]
**Describe the bug**
Typing /shop in-game produces a message saying that "an internal error has occurred" and causes an error in console. On server startup, there is a NoSuchFieldError in console.

**Expected behavior**
Plugin to load in without issue and open a GUI when /shop is entered. Be able to complete the creation of shops.

**Screenshots**
NoSuchFieldError on startup: https://gyazo.com/489c4237d42dbe3049bb97267baac021
Error message in-game when typing /shop: https://gyazo.com/89ad9a20a5735f2ea2d310dc54554572
Error message in console after typing /shop: https://gyazo.com/eb2b19f6f545e622917e55f4821e26b0

**Version:**
This issue is present with both spigot and craftbukkit.
I'm currently using bukkit, but the screenshots are from spigot. The error don't change.
 - Spigot version: 1.13.2
- Craftbukkit version: 1.13.2
 - Shop version 1.8.1

If anyone can help with this, I'd really appreciate it!

**Comment by BillyGalbreath** [comment]
1.8.1 is for 1.14+ servers. Since you use legacy server version you must use legacy plugin version. Use 1.8

**Comment by Verbannt** [comment]
Thanks for the response! I tried using v1.8 and there are no console errors on startup or errors when typing /shop. However, when someone tries to create a shop this error appears in console: https://gyazo.com/1e74dbf4155bcb4caceacc338da07bb1
