### ISSUE TITLE
Buy and sell shop on one chest.

### ISSUE THREAD

**Issue by Floffah** [snowgears/shopbugs#95]
**Is your feature request related to a problem? Please describe.**
its not really a problem but our players really want to be able to put buy and sell signs for the same item on one chest like you can in chestshop.

**Describe the solution you'd like**
To be able to put a buy and sell sign for one item on the same chest.

**Describe alternatives you've considered**
We used to use chestshop which had it but then moved to this because this is better but doesn't have this feature.

**Additional context**
If this is already a thing it is not documented or im blind and cant see it in the config.

**Comment by snowgears** [comment]
This is possible using double chests at the moment (one side for buying and one for selling)

**Comment by Floffah** [comment]
From my testing, when you try and put any sign on a double chest (even if there is no sign already) it says something about invalid side i can't remember the exact message.

**Comment by tWizT3ddreaMr** [comment]
Have you tried using a combo shop? Do you require it to be two signs?

**Comment by snowgears** [comment]
This is possible with a combo shop. Please see the "how to create different shops" FAQ on the main page.
