### ISSUE TITLE
Using Shop GUI lags the server

### ISSUE THREAD

**Issue by arizrain1** [snowgears/shopbugs#96]
Clicking the GUI shop choice crashed the server.  I understand you have not updated to 1.15.2, so if this is the issue, I understand.

But can you let me know if you will update this?

Thank you very much

Arizrain -  Rsmv.net

Console Error:   https://pastebin.com/Q0Pr6BNs

**Comment by snowgears** [comment]
Should be fixed in 1.8.2.8 (in progress)
