### ISSUE TITLE
Laggspike while opening a shop

### ISSUE THREAD

**Issue by martijnpu** [snowgears/shopbugs#97]
**Describe the bug**
Server freeses sometimes when someone opens a chest, kicking all online players

**Screenshots**
https://pastebin.com/ZypU2k8B

**Version:**
 - Spigot version: Latest Paper
 - Shop version 1.8.1

**Comment by tWizT3ddreaMr** [comment]
Opens a chest or opens the gui? The log you provided only shows gui classes.

**Comment by martijnpu** [comment]
That's right. I mean /shop. Where you can see all shops in the server.

Op zo 28 jun. 2020 06:14 schreef tWizT3ddreaMr <notifications@github.com>:

**Comment by snowgears** [comment]
Duplicate of #96
