### ISSUE TITLE
WorldGuardHook not generating flag

### ISSUE THREAD

**Issue by ghostryder13** [snowgears/shopbugs#98]
![Capture1](https://user-images.githubusercontent.com/16345918/84808077-26f9f900-afd6-11ea-9dce-50ffa51419cd.PNG)
![Capture2](https://user-images.githubusercontent.com/16345918/84808078-26f9f900-afd6-11ea-8f58-f3de82e7f822.PNG)

**Describe the bug**
When setting hookWorldGuard:true no flag is generated within worldguard to be added. After speaking with enginehub to discuss, they stated the plugin requesting a new flag generates the flag through the api. So either I am requesting to add the incorrect flag ( shop: allow ) or its not being generated correctly from what I can see.

I can add the flag manually, but still has no effect on region. Tried with permissions set to true as well in config

**Comment by tWizT3ddreaMr** [comment]
I think the flag was changed with the 1.8.1 release to allow-shop so try allow-shop: allow

**Comment by ghostryder13** [comment]
That was it!! thank you!

**Comment by ghostryder13** [comment]
Before I was doing testing with the plugin on a local hosted server. However since uploading to a bungeecord I get errors along this line

> 27.06 16:44:33 [Server] WARN Found wrong value for flag allow-shop

^^This seems to happen when allow-shop: deny is set as a flag. 

When it is set to allow-shop: allow I get this response:

> The plugin that registered this flag is not currently installed

Long story short, if a player has building privledges they are able to create a shop

**Comment by tWizT3ddreaMr** [comment]
Since it is bungeecord assuming you have the shop plugin on the server in question:
  Is there any error upon startup for the server in question
  And did you make sure to enable the hook on the server in question

**Comment by snowgears** [comment]
Included Billy's source for WorldGuard hook in 1.8.2.1. ❤️ Fixed.
