### ISSUE TITLE
Is the plugin compatible with 1.15?

### ISSUE THREAD

**Issue by srnyx** [snowgears/shopbugs#99]
**Is your feature request related to a problem? Please describe.**
I wanted to know if there are any plans for the plugin to be 1.15 compatible

**Describe the solution you'd like**
For the plugin to be compatible with Minecraft version 1.15+

**Describe alternatives you've considered**
None, this plugin is the best one I could find

**Additional context**
I just wanna know if it's compatible with 1.15 or if I use it on 1.15 and if some features may not work

**Comment by tWizT3ddreaMr** [comment]
Yes it works, but there are bugs as you can see by the open issues here. But it does work, however the gui does lag quite a bit.
